/// autogenerated by protoc-plugin-js
const assert = require('nanoassert')
const { enumerable } = require('protobuf-codec/encode/types')
const { enumerable: decodeEnumerable } = require('protobuf-codec/decode/types')

const TYPE_UNSPECIFIED = 0
const TYPE_STAKE_DEPOSITED = 1
const TYPE_STAKE_REMOVED = 2
const TYPE_FUNDS_DEPOSITED = 3
const TYPE_SIGNER_ADDED = 4
const TYPE_SIGNER_REMOVED = 5
const TYPE_BRIDGE_STOPPED = 6
const TYPE_BRIDGE_RESUMED = 7
const TYPE_ASSET_LISTED = 8
const TYPE_LIMITS_UPDATED = 9
const TYPE_STAKE_TOTAL_SUPPLY = 10
const TYPE_SIGNER_THRESHOLD_SET = 11
const TYPE_GOVERNANCE_VALIDATE_ASSET = 12
const TYPE_ETHEREUM_CONTRACT_CALL_RESULT = 13

const enumValues = new Map([
  [0, 'TYPE_UNSPECIFIED'],
  [1, 'TYPE_STAKE_DEPOSITED'],
  [2, 'TYPE_STAKE_REMOVED'],
  [3, 'TYPE_FUNDS_DEPOSITED'],
  [4, 'TYPE_SIGNER_ADDED'],
  [5, 'TYPE_SIGNER_REMOVED'],
  [6, 'TYPE_BRIDGE_STOPPED'],
  [7, 'TYPE_BRIDGE_RESUMED'],
  [8, 'TYPE_ASSET_LISTED'],
  [9, 'TYPE_LIMITS_UPDATED'],
  [10, 'TYPE_STAKE_TOTAL_SUPPLY'],
  [11, 'TYPE_SIGNER_THRESHOLD_SET'],
  [12, 'TYPE_GOVERNANCE_VALIDATE_ASSET'],
  [13, 'TYPE_ETHEREUM_CONTRACT_CALL_RESULT']
])
const enumNames = new Map([
  ['TYPE_UNSPECIFIED', 0],
  ['TYPE_STAKE_DEPOSITED', 1],
  ['TYPE_STAKE_REMOVED', 2],
  ['TYPE_FUNDS_DEPOSITED', 3],
  ['TYPE_SIGNER_ADDED', 4],
  ['TYPE_SIGNER_REMOVED', 5],
  ['TYPE_BRIDGE_STOPPED', 6],
  ['TYPE_BRIDGE_RESUMED', 7],
  ['TYPE_ASSET_LISTED', 8],
  ['TYPE_LIMITS_UPDATED', 9],
  ['TYPE_STAKE_TOTAL_SUPPLY', 10],
  ['TYPE_SIGNER_THRESHOLD_SET', 11],
  ['TYPE_GOVERNANCE_VALIDATE_ASSET', 12],
  ['TYPE_ETHEREUM_CONTRACT_CALL_RESULT', 13]
])

function encode(value, buf, byteOffset = 0) {
  if (typeof value === 'string') return encode(parse(value), buf, byteOffset)
  if (value == null) throw new Error('Invalid Type value (' + value + ')')

  return enumerable.encode(value, buf, byteOffset)
}

function decode(varint) {
  const int = decodeEnumerable(varint)

  return stringify(int) ?? int
}

function encodingLength(value) {
  if (typeof value === 'string') return encodingLength(parse(value))
  assert(value != null, 'Invalid Type value (' + value + ')')

  if (0 <= value && value <= 13) return 1

  // enumerable max value in case of unknown value
  return 5
}

/**
 * Convert an enum value to it's human readable name.
 * Returns undefined on an unknown value.
 */
function stringify(int) {
  return enumValues.get(int)
}

/**
 * Convert an enum string names to it's machine integer value.
 * Returns undefined on an unknown name.
 */
function parse(str) {
  return enumNames.get(str)
}

module.exports = {
  encode,
  decode,
  encodingLength,
  stringify,
  parse,
  TYPE_UNSPECIFIED,
  TYPE_STAKE_DEPOSITED,
  TYPE_STAKE_REMOVED,
  TYPE_FUNDS_DEPOSITED,
  TYPE_SIGNER_ADDED,
  TYPE_SIGNER_REMOVED,
  TYPE_BRIDGE_STOPPED,
  TYPE_BRIDGE_RESUMED,
  TYPE_ASSET_LISTED,
  TYPE_LIMITS_UPDATED,
  TYPE_STAKE_TOTAL_SUPPLY,
  TYPE_SIGNER_THRESHOLD_SET,
  TYPE_GOVERNANCE_VALIDATE_ASSET,
  TYPE_ETHEREUM_CONTRACT_CALL_RESULT
}
