/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')

const _vega_ActivityStreakBenefitTier = require('./../ActivityStreakBenefitTier/decode.js')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  const field$tiers = []
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$tiers.push(_vega_ActivityStreakBenefitTier.decode(data))
        break
    }
  }
  return { tiers: field$tiers }
}
