/// autogenerated by protoc-plugin-js
import type { ActivityStreakBenefitTiers } from '../ActivityStreakBenefitTiers'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): ActivityStreakBenefitTiers
