/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { ActivityStreakBenefitTiers } from '../ActivityStreakBenefitTiers'
export function encode(
  obj?: PartialDeep<ActivityStreakBenefitTiers>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
