/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { string } = require('protobuf-codec/decode/types')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$minimumQuantumBalance = ''
  let field$rewardMultiplier = ''
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$minimumQuantumBalance = string(data)
        break

      case 2:
        field$rewardMultiplier = string(data)
        break
    }
  }
  return {
    minimumQuantumBalance: field$minimumQuantumBalance,
    rewardMultiplier: field$rewardMultiplier
  }
}
