/// autogenerated by protoc-plugin-js
import type { VestingBenefitTier } from '../VestingBenefitTier'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): VestingBenefitTier
