'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');
var decode$1 = require('../Signature/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$nodeId = '';
  let field$ethereumSignature = {};
  let field$vegaSignature = {};
  let field$message = '';
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$nodeId = types.string(data);
        break

      case 2:
        field$ethereumSignature = decode$1.decode(data);
        break

      case 3:
        field$vegaSignature = decode$1.decode(data);
        break

      case 4:
        field$message = types.string(data);
        break
    }
  }
  return {
    nodeId: field$nodeId,
    ethereumSignature: field$ethereumSignature,
    vegaSignature: field$vegaSignature,
    message: field$message
  }
}

exports.decode = decode;
