'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');
var decode$1 = require('../../../DispatchStrategy/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$startEpoch = 0n;
  let field$endEpoch = null;
  let field$factor = '';
  let field$dispatchStrategy = {};
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$startEpoch = types.uint64(data);
        break

      case 2:
        field$endEpoch = types.uint64(data);
        break

      case 3:
        field$factor = types.string(data);
        break

      case 4:
        field$dispatchStrategy = decode$1.decode(data);
        break
    }
  }
  return {
    startEpoch: field$startEpoch,
    endEpoch: field$endEpoch,
    factor: field$factor,
    dispatchStrategy: field$dispatchStrategy
  }
}

exports.decode = decode;
