'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$proposed = 0n;
  let field$pending = 0n;
  let field$open = 0n;
  let field$close = 0n;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$proposed = types.int64(data);
        break

      case 2:
        field$pending = types.int64(data);
        break

      case 3:
        field$open = types.int64(data);
        break

      case 4:
        field$close = types.int64(data);
        break
    }
  }
  return {
    proposed: field$proposed,
    pending: field$pending,
    open: field$open,
    close: field$close
  }
}

exports.decode = decode;
