/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { EpochParticipation } from '../EpochParticipation'
export function encode(
  obj?: PartialDeep<EpochParticipation>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
