/// autogenerated by protoc-plugin-js
import type { MarketTimestamps } from '../MarketTimestamps'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): MarketTimestamps
