/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { MarketTimestamps } from '../MarketTimestamps'
export function encode(
  obj?: PartialDeep<MarketTimestamps>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
