/// autogenerated by protoc-plugin-js
import type { EVMBridgeConfigs } from '../EVMBridgeConfigs'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): EVMBridgeConfigs
