/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')

const _vega_EVMBridgeConfig = require('./../EVMBridgeConfig/decode.js')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  const field$configs = []
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$configs.push(_vega_EVMBridgeConfig.decode(data))
        break
    }
  }
  return { configs: field$configs }
}
