/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { EVMBridgeConfigs } from '../EVMBridgeConfigs'
export function encode(
  obj?: PartialDeep<EVMBridgeConfigs>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
