/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { string } = require('protobuf-codec/decode/types')
const _vega_AssetDetails = require('./../AssetDetails/decode.js')
const _vega_Asset_Status = require('./Status.js')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$id = ''
  let field$details = {}
  let field$status = _vega_Asset_Status.decode(0)
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$id = string(data)
        break

      case 2:
        field$details = _vega_AssetDetails.decode(data)
        break

      case 3:
        field$status = _vega_Asset_Status.decode(data)
        break
    }
  }
  return { id: field$id, details: field$details, status: field$status }
}
