/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { Asset } from '../Asset'
export function encode(
  obj?: PartialDeep<Asset>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
