'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.startTime) writer.varint(1, obj.startTime, types.int64);
  if (obj.expiryTime) writer.varint(2, obj.expiryTime, types.int64);
  if (obj.endTime) writer.varint(3, obj.endTime, types.int64);
  if (obj.firstBlock) writer.varint(4, obj.firstBlock, types.uint64);
  if (obj.lastBlock) writer.varint(5, obj.lastBlock, types.uint64);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
