/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { MarketData } from '../MarketData'
export function encode(
  obj?: PartialDeep<MarketData>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
