/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { PartyProfile } from '../PartyProfile'
export function encode(
  obj?: PartialDeep<PartyProfile>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
