/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { Normaliser } from '../Normaliser'
export function encode(
  obj?: PartialDeep<Normaliser>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
