'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$searchLevel = 0;
  let field$initialMargin = 0;
  let field$collateralRelease = 0;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$searchLevel = types.double(data);
        break

      case 2:
        field$initialMargin = types.double(data);
        break

      case 3:
        field$collateralRelease = types.double(data);
        break
    }
  }
  return {
    searchLevel: field$searchLevel,
    initialMargin: field$initialMargin,
    collateralRelease: field$collateralRelease
  }
}

exports.decode = decode;
