/// autogenerated by protoc-plugin-js
import type { EthereumL2Configs } from '../EthereumL2Configs'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): EthereumL2Configs
