/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { EthereumL2Configs } from '../EthereumL2Configs'
export function encode(
  obj?: PartialDeep<EthereumL2Configs>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
