/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { ERC20SignerRemoved } from '../ERC20SignerRemoved'
export function encode(
  obj?: PartialDeep<ERC20SignerRemoved>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
