/// autogenerated by protoc-plugin-js
import type { IssueSignatures } from '../IssueSignatures'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): IssueSignatures
