/// autogenerated by protoc-plugin-js
import type { CreateReferralSet } from '../CreateReferralSet'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): CreateReferralSet
