/// autogenerated by protoc-plugin-js
import type { ExternalDataSourceSpec } from '../ExternalDataSourceSpec'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): ExternalDataSourceSpec
