'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');
var encode$1 = require('../ERC20Update/encode.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.quantum) writer.bytes(5, obj.quantum, types.string);

  if (obj.source?.erc20 ?? obj.erc20)
    writer.bytes(101, encode$1.encode(obj.source?.erc20 ?? obj.erc20));

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
