/// autogenerated by protoc-plugin-js
import type { VolumeDiscountProgram } from '../VolumeDiscountProgram'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): VolumeDiscountProgram
