'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$assetId = '';
  let field$partyId = '';
  let field$epoch = 0n;
  let field$amount = '';
  let field$percentageOfTotal = '';
  let field$receivedAt = 0n;
  let field$marketId = '';
  let field$rewardType = '';
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$assetId = types.string(data);
        break

      case 2:
        field$partyId = types.string(data);
        break

      case 3:
        field$epoch = types.uint64(data);
        break

      case 4:
        field$amount = types.string(data);
        break

      case 5:
        field$percentageOfTotal = types.string(data);
        break

      case 6:
        field$receivedAt = types.int64(data);
        break

      case 7:
        field$marketId = types.string(data);
        break

      case 8:
        field$rewardType = types.string(data);
        break
    }
  }
  return {
    assetId: field$assetId,
    partyId: field$partyId,
    epoch: field$epoch,
    amount: field$amount,
    percentageOfTotal: field$percentageOfTotal,
    receivedAt: field$receivedAt,
    marketId: field$marketId,
    rewardType: field$rewardType
  }
}

exports.decode = decode;
