'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.assetId) writer.bytes(1, obj.assetId, types.string);
  if (obj.partyId) writer.bytes(2, obj.partyId, types.string);
  if (obj.epoch) writer.varint(3, obj.epoch, types.uint64);
  if (obj.amount) writer.bytes(4, obj.amount, types.string);
  if (obj.percentageOfTotal) writer.bytes(5, obj.percentageOfTotal, types.string);
  if (obj.receivedAt) writer.varint(6, obj.receivedAt, types.int64);
  if (obj.marketId) writer.bytes(7, obj.marketId, types.string);
  if (obj.rewardType) writer.bytes(8, obj.rewardType, types.string);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
