/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { UpdateMarginMode } from '../UpdateMarginMode'
export function encode(
  obj?: PartialDeep<UpdateMarginMode>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
