/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { DiscountFactors } from '../DiscountFactors'
export function encode(
  obj?: PartialDeep<DiscountFactors>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
