'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$epoch = 0n;
  let field$assetId = '';
  let field$marketId = '';
  let field$rewardType = '';
  let field$amount = '';
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$epoch = types.uint64(data);
        break

      case 2:
        field$assetId = types.string(data);
        break

      case 3:
        field$marketId = types.string(data);
        break

      case 4:
        field$rewardType = types.string(data);
        break

      case 5:
        field$amount = types.string(data);
        break
    }
  }
  return {
    epoch: field$epoch,
    assetId: field$assetId,
    marketId: field$marketId,
    rewardType: field$rewardType,
    amount: field$amount
  }
}

exports.decode = decode;
