'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$assetId = '';
  let field$partyId = '';
  let field$amount = '';
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$assetId = types.string(data);
        break

      case 2:
        field$partyId = types.string(data);
        break

      case 3:
        field$amount = types.string(data);
        break
    }
  }
  return {
    assetId: field$assetId,
    partyId: field$partyId,
    amount: field$amount
  }
}

exports.decode = decode;
