/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { ReferralProgram } from '../ReferralProgram'
export function encode(
  obj?: PartialDeep<ReferralProgram>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
