/// autogenerated by protoc-plugin-js
import type { PerpetualProduct } from '../PerpetualProduct'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): PerpetualProduct
