/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { LiquidityProvisionSubmission } from '../LiquidityProvisionSubmission'
export function encode(
  obj?: PartialDeep<LiquidityProvisionSubmission>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
