/// autogenerated by protoc-plugin-js
import type { BatchProposalTermsChange } from '../BatchProposalTermsChange'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): BatchProposalTermsChange
