/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { DataSourceSpec } from '../DataSourceSpec'
export function encode(
  obj?: PartialDeep<DataSourceSpec>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
