/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { string, uint64, int64, bool } = require('protobuf-codec/encode/types')
const _vega_Side = require('./../Side.js')
const _vega_Order_TimeInForce = require('./TimeInForce.js')
const _vega_Order_Type = require('./Type.js')
const _vega_Order_Status = require('./Status.js')
const _vega_OrderError = require('./../OrderError.js')
const _vega_PeggedOrder = require('./../PeggedOrder/encode.js')
const _vega_IcebergOrder = require('./../IcebergOrder/encode.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.id) writer.bytes(1, obj.id, string)
  if (obj.marketId) writer.bytes(2, obj.marketId, string)
  if (obj.partyId) writer.bytes(3, obj.partyId, string)
  if (obj.side) writer.varint(4, obj.side, _vega_Side)
  if (obj.price) writer.bytes(5, obj.price, string)
  if (obj.size) writer.varint(6, obj.size, uint64)
  if (obj.remaining) writer.varint(7, obj.remaining, uint64)
  if (obj.timeInForce)
    writer.varint(8, obj.timeInForce, _vega_Order_TimeInForce)
  if (obj.type) writer.varint(9, obj.type, _vega_Order_Type)
  if (obj.createdAt) writer.varint(10, obj.createdAt, int64)
  if (obj.status) writer.varint(11, obj.status, _vega_Order_Status)
  if (obj.expiresAt) writer.varint(12, obj.expiresAt, int64)
  if (obj.reference) writer.bytes(13, obj.reference, string)
  if (obj.reason) writer.varint(14, obj.reason, _vega_OrderError)
  if (obj.updatedAt) writer.varint(15, obj.updatedAt, int64)
  if (obj.version) writer.varint(16, obj.version, uint64)
  if (obj.batchId) writer.varint(17, obj.batchId, uint64)
  if (obj.peggedOrder)
    writer.bytes(18, _vega_PeggedOrder.encode(obj.peggedOrder))
  if (obj.liquidityProvisionId)
    writer.bytes(19, obj.liquidityProvisionId, string)
  if (obj.postOnly) writer.varint(20, obj.postOnly, bool)
  if (obj.reduceOnly) writer.varint(21, obj.reduceOnly, bool)
  if (obj.icebergOrder)
    writer.bytes(22, _vega_IcebergOrder.encode(obj.icebergOrder))

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
