/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { Order } from '../Order'
export function encode(
  obj?: PartialDeep<Order>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
