/// autogenerated by protoc-plugin-js
import type { LiteralUnion } from 'type-fest'

export const STATUS_UNSPECIFIED = 0
export const STATUS_ACTIVE = 1
export const STATUS_EXPIRED = 2
export const STATUS_CANCELLED = 3
export const STATUS_STOPPED = 4
export const STATUS_FILLED = 5
export const STATUS_REJECTED = 6
export const STATUS_PARTIALLY_FILLED = 7
export const STATUS_PARKED = 8

export type Values = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8
export type Names =
  | 'STATUS_UNSPECIFIED'
  | 'STATUS_ACTIVE'
  | 'STATUS_EXPIRED'
  | 'STATUS_CANCELLED'
  | 'STATUS_STOPPED'
  | 'STATUS_FILLED'
  | 'STATUS_REJECTED'
  | 'STATUS_PARTIALLY_FILLED'
  | 'STATUS_PARKED'

export const enum Status {
  STATUS_UNSPECIFIED = 0,
  STATUS_ACTIVE = 1,
  STATUS_EXPIRED = 2,
  STATUS_CANCELLED = 3,
  STATUS_STOPPED = 4,
  STATUS_FILLED = 5,
  STATUS_REJECTED = 6,
  STATUS_PARTIALLY_FILLED = 7,
  STATUS_PARKED = 8
}

declare const enumValues: Map<Names, Values>
declare const enumNames: Map<Values, Names>

export function encode(
  value: Values | Names,
  buf: Uint8Array,
  byteOffset: number
): Uint8Array

export function decode(varint: bigint): LiteralUnion<Names, number>

export function encodingLength(value: LiteralUnion<Values, number>): number

export function stringify(int: Values): LiteralUnion<Names, undefined>

export function parse(str: Names): LiteralUnion<Values, undefined>
