/// autogenerated by protoc-plugin-js
import type { KeyValueBundle } from '../KeyValueBundle'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): KeyValueBundle
