'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');
var decode$1 = require('../TargetStakeParameters/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$targetStakeParameters = {};
  let field$triggeringRatio = '';
  let field$auctionExtension = 0n;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$targetStakeParameters = decode$1.decode(data);
        break

      case 2:
        field$triggeringRatio = types.string(data);
        break

      case 3:
        field$auctionExtension = types.int64(data);
        break
    }
  }
  return {
    targetStakeParameters: field$targetStakeParameters,
    triggeringRatio: field$triggeringRatio,
    auctionExtension: field$auctionExtension
  }
}

exports.decode = decode;
