'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$party = '';
  let field$equityLikeShare = '';
  let field$averageEntryValuation = '';
  let field$averageScore = '';
  let field$virtualStake = '';
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$party = types.string(data);
        break

      case 2:
        field$equityLikeShare = types.string(data);
        break

      case 3:
        field$averageEntryValuation = types.string(data);
        break

      case 4:
        field$averageScore = types.string(data);
        break

      case 5:
        field$virtualStake = types.string(data);
        break
    }
  }
  return {
    party: field$party,
    equityLikeShare: field$equityLikeShare,
    averageEntryValuation: field$averageEntryValuation,
    averageScore: field$averageScore,
    virtualStake: field$virtualStake
  }
}

exports.decode = decode;
