/// autogenerated by protoc-plugin-js

module.exports = {
  ...require('./AmendAMM/encode.js'),
  ...require('./AmendAMM/decode.js'),
  ConcentratedLiquidityParameters: require('./AmendAMM/ConcentratedLiquidityParameters.js')
}
