/// autogenerated by protoc-plugin-js
import type { BatchProposalSubmissionTerms } from './BatchProposalSubmissionTerms'
import type { ProposalRationale } from './../../ProposalRationale'

export * from './BatchProposalSubmission/encode.js'
export * from './BatchProposalSubmission/decode.js'

export type BatchProposalSubmission = {
  reference: string
  terms: BatchProposalSubmissionTerms
  rationale: ProposalRationale
}
