/// autogenerated by protoc-plugin-js
import type { Team } from './CreateReferralSet/Team'

export * from './CreateReferralSet/encode.js'
export * from './CreateReferralSet/decode.js'

export * as Team from './CreateReferralSet/Team.js'

export type CreateReferralSet = {
  isTeam: boolean
  team: Team | null
  doNotCreateReferralSet: boolean
}
