/// autogenerated by protoc-plugin-js

export * from './CreateTeam/encode.js'
export * from './CreateTeam/decode.js'

export type CreateTeam = {
  enableRewards: boolean
  name: string | null
  teamUrl: string | null
  avatarUrl: string | null
}
