/// autogenerated by protoc-plugin-js

export * from './DelayedTransactionsWrapper/encode.js'
export * from './DelayedTransactionsWrapper/decode.js'

export type DelayedTransactionsWrapper = {
  transactions: Uint8Array[]
}
