/// autogenerated by protoc-plugin-js

export * from './LiquidityProvisionAmendment/encode.js'
export * from './LiquidityProvisionAmendment/decode.js'

export type LiquidityProvisionAmendment = {
  marketId: string
  commitmentAmount: string
  fee: string
  reference: string
}
