/// autogenerated by protoc-plugin-js
const assert = require('nanoassert')
const { enumerable } = require('protobuf-codec/encode/types')
const { enumerable: decodeEnumerable } = require('protobuf-codec/decode/types')

const NODE_SIGNATURE_KIND_UNSPECIFIED = 0
const NODE_SIGNATURE_KIND_ASSET_NEW = 1
const NODE_SIGNATURE_KIND_ASSET_WITHDRAWAL = 2
const NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_ADDED = 3
const NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_REMOVED = 4
const NODE_SIGNATURE_KIND_ASSET_UPDATE = 5

const enumValues = new Map([
  [0, 'NODE_SIGNATURE_KIND_UNSPECIFIED'],
  [1, 'NODE_SIGNATURE_KIND_ASSET_NEW'],
  [2, 'NODE_SIGNATURE_KIND_ASSET_WITHDRAWAL'],
  [3, 'NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_ADDED'],
  [4, 'NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_REMOVED'],
  [5, 'NODE_SIGNATURE_KIND_ASSET_UPDATE']
])
const enumNames = new Map([
  ['NODE_SIGNATURE_KIND_UNSPECIFIED', 0],
  ['NODE_SIGNATURE_KIND_ASSET_NEW', 1],
  ['NODE_SIGNATURE_KIND_ASSET_WITHDRAWAL', 2],
  ['NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_ADDED', 3],
  ['NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_REMOVED', 4],
  ['NODE_SIGNATURE_KIND_ASSET_UPDATE', 5]
])

function encode(value, buf, byteOffset = 0) {
  if (typeof value === 'string') return encode(parse(value), buf, byteOffset)
  if (value == null)
    throw new Error('Invalid NodeSignatureKind value (' + value + ')')

  return enumerable.encode(value, buf, byteOffset)
}

function decode(varint) {
  const int = decodeEnumerable(varint)

  return stringify(int) ?? int
}

function encodingLength(value) {
  if (typeof value === 'string') return encodingLength(parse(value))
  assert(value != null, 'Invalid NodeSignatureKind value (' + value + ')')

  if (0 <= value && value <= 5) return 1

  // enumerable max value in case of unknown value
  return 5
}

/**
 * Convert an enum value to it's human readable name.
 * Returns undefined on an unknown value.
 */
function stringify(int) {
  return enumValues.get(int)
}

/**
 * Convert an enum string names to it's machine integer value.
 * Returns undefined on an unknown name.
 */
function parse(str) {
  return enumNames.get(str)
}

module.exports = {
  encode,
  decode,
  encodingLength,
  stringify,
  parse,
  NODE_SIGNATURE_KIND_UNSPECIFIED,
  NODE_SIGNATURE_KIND_ASSET_NEW,
  NODE_SIGNATURE_KIND_ASSET_WITHDRAWAL,
  NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_ADDED,
  NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_REMOVED,
  NODE_SIGNATURE_KIND_ASSET_UPDATE
}
