/// autogenerated by protoc-plugin-js
import type { TimeInForce } from './../../Order/TimeInForce'
import type { PeggedReference } from './../../PeggedReference'

export * from './OrderAmendment/encode.js'
export * from './OrderAmendment/decode.js'

export type OrderAmendment = {
  orderId: string
  marketId: string
  price: string | null
  sizeDelta: bigint
  expiresAt: bigint | null
  timeInForce: TimeInForce
  peggedOffset: string
  peggedReference: PeggedReference
}
