/// autogenerated by protoc-plugin-js
import type { ProposalTerms } from './../../ProposalTerms'
import type { ProposalRationale } from './../../ProposalRationale'

export * from './ProposalSubmission/encode.js'
export * from './ProposalSubmission/decode.js'

export type ProposalSubmission = {
  reference: string
  terms: ProposalTerms
  rationale: ProposalRationale
}
