/// autogenerated by protoc-plugin-js
import type { StateValueProposal } from './../../StateValueProposal'

export * from './StateVariableProposal/encode.js'
export * from './StateVariableProposal/decode.js'

export type StateVariableProposal = {
  proposal: StateValueProposal
}
