/// autogenerated by protoc-plugin-js
import type { OrderSubmission } from './OrderSubmission'
import type { ExpiryStrategy } from './../../StopOrder/ExpiryStrategy'
import type { SizeOverrideSetting } from './../../StopOrder/SizeOverrideSetting'
import type { SizeOverrideValue } from './../../StopOrder/SizeOverrideValue'

export * from './StopOrderSetup/encode.js'
export * from './StopOrderSetup/decode.js'

export type StopOrderSetup = {
  orderSubmission: OrderSubmission
  expiresAt: bigint | null
  expiryStrategy: ExpiryStrategy | null
  sizeOverrideSetting: SizeOverrideSetting | null
  sizeOverrideValue: SizeOverrideValue | null
  trigger: { price: string } | { trailingPercentOffset: string } | null
}
