/// autogenerated by protoc-plugin-js
import type { Signature } from './Signature'
import type { TxVersion } from './TxVersion'
import type { ProofOfWork } from './ProofOfWork'

export * from './Transaction/encode.js'
export * from './Transaction/decode.js'

export type Transaction = {
  inputData: Uint8Array
  signature: Signature
  from: { address: string } | { pubKey: string } | null
  version: TxVersion
  pow: ProofOfWork
}
