/// autogenerated by protoc-plugin-js
import type { AccountType } from './../../AccountType'
import type { OneOffTransfer } from './OneOffTransfer'
import type { RecurringTransfer } from './RecurringTransfer'

export * from './Transfer/encode.js'
export * from './Transfer/decode.js'

export type Transfer = {
  fromAccountType: AccountType
  to: string
  toAccountType: AccountType
  asset: string
  amount: string
  reference: string
  from: string | null
  kind: { oneOff: OneOffTransfer } | { recurring: RecurringTransfer } | null
}
