/// autogenerated by protoc-plugin-js
import type { Team } from './UpdateReferralSet/Team'

export * from './UpdateReferralSet/encode.js'
export * from './UpdateReferralSet/decode.js'

export * as Team from './UpdateReferralSet/Team.js'

export type UpdateReferralSet = {
  id: string
  isTeam: boolean
  team: Team | null
}
