/// autogenerated by protoc-plugin-js
import type { Mode } from './UpdateMarginMode/Mode'

export * from './UpdateMarginMode/encode.js'
export * from './UpdateMarginMode/decode.js'
export * as Mode from './UpdateMarginMode/Mode.js'

export type UpdateMarginMode = {
  marketId: string
  mode: Mode
  marginFactor: string | null
}
