/// autogenerated by protoc-plugin-js
import type { TradableInstrument } from '../TradableInstrument'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): TradableInstrument
