'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$vegaAssetId = '';
  let field$targetEthereumAddress = '';
  let field$referenceNonce = '';
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$vegaAssetId = types.string(data);
        break

      case 2:
        field$targetEthereumAddress = types.string(data);
        break

      case 3:
        field$referenceNonce = types.string(data);
        break
    }
  }
  return {
    vegaAssetId: field$vegaAssetId,
    targetEthereumAddress: field$targetEthereumAddress,
    referenceNonce: field$referenceNonce
  }
}

exports.decode = decode;
