/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { ERC20Heartbeat } from '../ERC20Heartbeat'
export function encode(
  obj?: PartialDeep<ERC20Heartbeat>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
