/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { string, uint64 } = require('protobuf-codec/encode/types')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.contractAddress) writer.bytes(1, obj.contractAddress, string)
  if (obj.blockHeight) writer.varint(2, obj.blockHeight, uint64)
  if (obj.blockTime) writer.varint(3, obj.blockTime, uint64)
  if (obj.sourceChainId) writer.bytes(6, obj.sourceChainId, string)

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
