'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$marketId = '';
  let field$indicativePrice = '';
  let field$indicativeVolume = 0n;
  let field$auctionStart = 0n;
  let field$auctionEnd = 0n;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$marketId = types.string(data);
        break

      case 2:
        field$indicativePrice = types.string(data);
        break

      case 3:
        field$indicativeVolume = types.uint64(data);
        break

      case 4:
        field$auctionStart = types.int64(data);
        break

      case 5:
        field$auctionEnd = types.int64(data);
        break
    }
  }
  return {
    marketId: field$marketId,
    indicativePrice: field$indicativePrice,
    indicativeVolume: field$indicativeVolume,
    auctionStart: field$auctionStart,
    auctionEnd: field$auctionEnd
  }
}

exports.decode = decode;
