/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { string } = require('protobuf-codec/encode/types')
const _vega_Metadata = require('./../../../Metadata/encode.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.alias) writer.bytes(1, obj.alias, string)
  if (obj.metadata?.length)
    obj.metadata.forEach((v) => writer.bytes(2, _vega_Metadata.encode(v)))

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
