/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { UpdatePartyProfile } from '../UpdatePartyProfile'
export function encode(
  obj?: PartialDeep<UpdatePartyProfile>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
