/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { RankingScore } from '../RankingScore'
export function encode(
  obj?: PartialDeep<RankingScore>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
