'use strict';

var encode = require('./NoPartyEntry/encode.cjs');
var decode = require('./NoPartyEntry/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
