/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { BatchProposalTerms } from '../BatchProposalTerms'
export function encode(
  obj?: PartialDeep<BatchProposalTerms>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
