/// autogenerated by protoc-plugin-js
import type { DispatchStrategy } from '../DispatchStrategy'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): DispatchStrategy
