/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { string } = require('protobuf-codec/encode/types')
const _vega_DispatchMetric = require('./../DispatchMetric.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.assetForMetric) writer.bytes(1, obj.assetForMetric, string)
  if (obj.metric) writer.varint(2, obj.metric, _vega_DispatchMetric)
  if (obj.markets?.length)
    obj.markets.forEach((v) => writer.bytes(3, v, string))

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
