'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');
var Method = require('./Method.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$nodeId = '';
  let field$amount = '';
  let field$method = 0;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$nodeId = types.string(data);
        break

      case 2:
        field$amount = types.string(data);
        break

      case 3:
        field$method =
          Method.decode(data);
        break
    }
  }
  return { nodeId: field$nodeId, amount: field$amount, method: field$method }
}

exports.decode = decode;
