/// autogenerated by protoc-plugin-js
import type { ReferralProgramChanges } from '../ReferralProgramChanges'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): ReferralProgramChanges
