'use strict';

var reader = require('protobuf-codec/decode/reader');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
  }
  return {}
}

exports.decode = decode;
