/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { RewardFactors } from '../RewardFactors'
export function encode(
  obj?: PartialDeep<RewardFactors>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
