/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { string } = require('protobuf-codec/encode/types')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.infrastructureRewardFactor)
    writer.bytes(1, obj.infrastructureRewardFactor, string)
  if (obj.liquidityRewardFactor)
    writer.bytes(2, obj.liquidityRewardFactor, string)
  if (obj.makerRewardFactor) writer.bytes(3, obj.makerRewardFactor, string)

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
