'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');
var decode$1 = require('../LogNormalModelParams/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$riskAversionParameter = 0;
  let field$tau = 0;
  let field$params = {};
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$riskAversionParameter = types.double(data);
        break

      case 2:
        field$tau = types.double(data);
        break

      case 3:
        field$params = decode$1.decode(data);
        break
    }
  }
  return {
    riskAversionParameter: field$riskAversionParameter,
    tau: field$tau,
    params: field$params
  }
}

exports.decode = decode;
