'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');
var encode$1 = require('../LogNormalModelParams/encode.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.riskAversionParameter)
    writer.fixed64(1, obj.riskAversionParameter, types.double);
  if (obj.tau) writer.fixed64(2, obj.tau, types.double);
  if (obj.params) writer.bytes(3, encode$1.encode(obj.params));

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
