/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { EthereumKeyRotateSubmission } from '../EthereumKeyRotateSubmission'
export function encode(
  obj?: PartialDeep<EthereumKeyRotateSubmission>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
