'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$market = '';
  let field$short = '';
  let field$long = '';
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$market = types.string(data);
        break

      case 2:
        field$short = types.string(data);
        break

      case 3:
        field$long = types.string(data);
        break
    }
  }
  return { market: field$market, short: field$short, long: field$long }
}

exports.decode = decode;
