/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { int64, double } = require('protobuf-codec/decode/types')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$timeWindow = 0n
  let field$scalingFactor = 0
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$timeWindow = int64(data)
        break

      case 2:
        field$scalingFactor = double(data)
        break
    }
  }
  return { timeWindow: field$timeWindow, scalingFactor: field$scalingFactor }
}
