/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { TargetStakeParameters } from '../TargetStakeParameters'
export function encode(
  obj?: PartialDeep<TargetStakeParameters>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
