'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');
var encode$1 = require('../FinancialAmount/encode.cjs');
var TransferType = require('../TransferType.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.owner) writer.bytes(1, obj.owner, types.string);
  if (obj.amount) writer.bytes(2, encode$1.encode(obj.amount));
  if (obj.type) writer.varint(3, obj.type, TransferType);
  if (obj.minAmount) writer.bytes(4, obj.minAmount, types.string);
  if (obj.marketId) writer.bytes(5, obj.marketId, types.string);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
