'use strict';

var encode = require('./AssetDetailsUpdate/encode.cjs');
var decode = require('./AssetDetailsUpdate/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
