'use strict';

var encode = require('./CancelTransferConfiguration/encode.cjs');
var decode = require('./CancelTransferConfiguration/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
