'use strict';

var encode = require('./Candle/encode.cjs');
var decode = require('./Candle/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
