'use strict';

var encode = require('./DataSourceSpecConfiguration/encode.cjs');
var decode = require('./DataSourceSpecConfiguration/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
