'use strict';

var encode = require('./DataSourceDefinitionExternal/encode.cjs');
var decode = require('./DataSourceDefinitionExternal/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
