'use strict';

var encode = require('./DataSourceDefinitionInternal/encode.cjs');
var decode = require('./DataSourceDefinitionInternal/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
