'use strict';

var encode = require('./Delegation/encode.cjs');
var decode = require('./Delegation/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
