'use strict';

var encode = require('./Deposit/encode.cjs');
var decode = require('./Deposit/decode.cjs');
var Status = require('./Deposit/Status.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
exports.Status = Status;
