'use strict';

var encode = require('./EpochParticipation/encode.cjs');
var decode = require('./EpochParticipation/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
