'use strict';

var encode = require('./EpochTimestamps/encode.cjs');
var decode = require('./EpochTimestamps/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
