'use strict';

var encode = require('./ERC20/encode.cjs');
var decode = require('./ERC20/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
