'use strict';

var encode = require('./ERC20Update/encode.cjs');
var decode = require('./ERC20Update/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
