'use strict';

var encode = require('./EthereumConfig/encode.cjs');
var decode = require('./EthereumConfig/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
