'use strict';

var encode = require('./EthTimeTrigger/encode.cjs');
var decode = require('./EthTimeTrigger/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
