'use strict';

var encode = require('./ExternalDataSourceSpec/encode.cjs');
var decode = require('./ExternalDataSourceSpec/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
