'use strict';

var encode = require('./FeeFactors/encode.cjs');
var decode = require('./FeeFactors/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
