'use strict';

var encode = require('./FinancialAmount/encode.cjs');
var decode = require('./FinancialAmount/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
