'use strict';

var encode = require('./GovernanceData/encode.cjs');
var decode = require('./GovernanceData/decode.cjs');
var YesPartyEntry = require('./GovernanceData/YesPartyEntry.cjs');
var NoPartyEntry = require('./GovernanceData/NoPartyEntry.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
exports.YesPartyEntry = YesPartyEntry;
exports.NoPartyEntry = NoPartyEntry;
