'use strict';

var assert = require('nanoassert');
var types = require('protobuf-codec/encode/types');
var types$1 = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

const GOVERNANCE_TRANSFER_TYPE_UNSPECIFIED = 0;
const GOVERNANCE_TRANSFER_TYPE_ALL_OR_NOTHING = 1;
const GOVERNANCE_TRANSFER_TYPE_BEST_EFFORT = 2;

const enumValues = new Map([
  [0, 'GOVERNANCE_TRANSFER_TYPE_UNSPECIFIED'],
  [1, 'GOVERNANCE_TRANSFER_TYPE_ALL_OR_NOTHING'],
  [2, 'GOVERNANCE_TRANSFER_TYPE_BEST_EFFORT']
]);
const enumNames = new Map([
  ['GOVERNANCE_TRANSFER_TYPE_UNSPECIFIED', 0],
  ['GOVERNANCE_TRANSFER_TYPE_ALL_OR_NOTHING', 1],
  ['GOVERNANCE_TRANSFER_TYPE_BEST_EFFORT', 2]
]);

function encode(value, buf, byteOffset = 0) {
  if (typeof value === 'string') return encode(parse(value), buf, byteOffset)
  if (value == null)
    throw new Error('Invalid GovernanceTransferType value (' + value + ')')

  return types.enumerable.encode(value, buf, byteOffset)
}

function decode(varint) {
  const int = types$1.enumerable(varint);

  return stringify(int) ?? int
}

function encodingLength(value) {
  if (typeof value === 'string') return encodingLength(parse(value))
  assert(value != null, 'Invalid GovernanceTransferType value (' + value + ')');

  if (0 <= value && value <= 2) return 1

  // enumerable max value in case of unknown value
  return 5
}

/**
 * Convert an enum value to it's human readable name.
 * Returns undefined on an unknown value.
 */
function stringify(int) {
  return enumValues.get(int)
}

/**
 * Convert an enum string names to it's machine integer value.
 * Returns undefined on an unknown name.
 */
function parse(str) {
  return enumNames.get(str)
}

exports.GOVERNANCE_TRANSFER_TYPE_ALL_OR_NOTHING = GOVERNANCE_TRANSFER_TYPE_ALL_OR_NOTHING;
exports.GOVERNANCE_TRANSFER_TYPE_BEST_EFFORT = GOVERNANCE_TRANSFER_TYPE_BEST_EFFORT;
exports.GOVERNANCE_TRANSFER_TYPE_UNSPECIFIED = GOVERNANCE_TRANSFER_TYPE_UNSPECIFIED;
exports.decode = decode;
exports.encode = encode;
exports.encodingLength = encodingLength;
exports.parse = parse;
exports.stringify = stringify;
