'use strict';

var encode = require('./IcebergOrder/encode.cjs');
var decode = require('./IcebergOrder/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
