'use strict';

var encode = require('./InstrumentMetadata/encode.cjs');
var decode = require('./InstrumentMetadata/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
