'use strict';

var encode = require('./LedgerMovement/encode.cjs');
var decode = require('./LedgerMovement/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
