'use strict';

var encode = require('./LiquidityProviderFeeShare/encode.cjs');
var decode = require('./LiquidityProviderFeeShare/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
