'use strict';

var encode = require('./LiquidityMonitoringParameters/encode.cjs');
var decode = require('./LiquidityMonitoringParameters/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
