'use strict';

var encode = require('./MarginCalculator/encode.cjs');
var decode = require('./MarginCalculator/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
