'use strict';

var encode = require('./MarketDepthUpdate/encode.cjs');
var decode = require('./MarketDepthUpdate/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
