'use strict';

var encode = require('./MarketDepth/encode.cjs');
var decode = require('./MarketDepth/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
