'use strict';

var encode = require('./NetworkLimits/encode.cjs');
var decode = require('./NetworkLimits/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
