'use strict';

var encode = require('./NewSpotMarket/encode.cjs');
var decode = require('./NewSpotMarket/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
