'use strict';

var encode = require('./NewTransfer/encode.cjs');
var decode = require('./NewTransfer/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
