'use strict';

var encode = require('./Node/encode.cjs');
var decode = require('./Node/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
