'use strict';

var encode = require('./Party/encode.cjs');
var decode = require('./Party/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
