'use strict';

var encode = require('./PostTransferBalance/encode.cjs');
var decode = require('./PostTransferBalance/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
