'use strict';

var encode = require('./PriceMonitoringTrigger/encode.cjs');
var decode = require('./PriceMonitoringTrigger/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
