'use strict';

var encode = require('./PriceMonitoringParameters/encode.cjs');
var decode = require('./PriceMonitoringParameters/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
