'use strict';

var encode = require('./PriceLevel/encode.cjs');
var decode = require('./PriceLevel/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
