'use strict';

var encode = require('./PriceMonitoringSettings/encode.cjs');
var decode = require('./PriceMonitoringSettings/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
