'use strict';

var encode = require('./PriceMonitoringBounds/encode.cjs');
var decode = require('./PriceMonitoringBounds/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
