'use strict';

var encode = require('./Proposal/encode.cjs');
var decode = require('./Proposal/decode.cjs');
var State = require('./Proposal/State.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
exports.State = State;
