'use strict';

var encode = require('./RecurringTransfer/encode.cjs');
var decode = require('./RecurringTransfer/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
