'use strict';

var encode = require('./RewardSummary/encode.cjs');
var decode = require('./RewardSummary/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
