'use strict';

var encode = require('./ScalingFactors/encode.cjs');
var decode = require('./ScalingFactors/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
