'use strict';

var encode = require('./SimpleModelParams/encode.cjs');
var decode = require('./SimpleModelParams/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
