'use strict';

var encode = require('./SimpleRiskModel/encode.cjs');
var decode = require('./SimpleRiskModel/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
