'use strict';

var encode = require('./StakeDeposited/encode.cjs');
var decode = require('./StakeDeposited/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
