'use strict';

var encode = require('./StateVarValue/encode.cjs');
var decode = require('./StateVarValue/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
