'use strict';

var encode = require('./Transfer/encode.cjs');
var decode = require('./Transfer/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
