'use strict';

var encode = require('./TransferRequest/encode.cjs');
var decode = require('./TransferRequest/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
