'use strict';

var encode = require('./UpdateFutureProduct/encode.cjs');
var decode = require('./UpdateFutureProduct/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
