'use strict';

var encode = require('./UpdateMarketConfiguration/encode.cjs');
var decode = require('./UpdateMarketConfiguration/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
