'use strict';

var encode = require('./VectorValue/encode.cjs');
var decode = require('./VectorValue/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
