'use strict';

var encode = require('./Vote/encode.cjs');
var decode = require('./Vote/decode.cjs');
var Value = require('./Vote/Value.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
exports.Value = Value;
