'use strict';

var encode = require('./WithdrawExt/encode.cjs');
var decode = require('./WithdrawExt/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
