/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { LedgerEntry } from '../LedgerEntry'
export function encode(
  obj?: PartialDeep<LedgerEntry>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
