/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { string, int64 } = require('protobuf-codec/encode/types')
const _vega_AccountDetails = require('./../AccountDetails/encode.js')
const _vega_TransferType = require('./../TransferType.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.fromAccount)
    writer.bytes(1, _vega_AccountDetails.encode(obj.fromAccount))
  if (obj.toAccount) writer.bytes(2, _vega_AccountDetails.encode(obj.toAccount))
  if (obj.amount) writer.bytes(3, obj.amount, string)
  if (obj.type) writer.varint(4, obj.type, _vega_TransferType)
  if (obj.timestamp) writer.varint(5, obj.timestamp, int64)
  if (obj.fromAccountBalance) writer.bytes(6, obj.fromAccountBalance, string)
  if (obj.toAccountBalance) writer.bytes(7, obj.toAccountBalance, string)
  if (obj.transferId) writer.bytes(8, obj.transferId, string)

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
