/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')

const _vega_LongBlockAuction = require('./../LongBlockAuction/decode.js')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  const field$thresholdAndDuration = []
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$thresholdAndDuration.push(_vega_LongBlockAuction.decode(data))
        break
    }
  }
  return { thresholdAndDuration: field$thresholdAndDuration }
}
