/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { LongBlockAuctionDurationTable } from '../LongBlockAuctionDurationTable'
export function encode(
  obj?: PartialDeep<LongBlockAuctionDurationTable>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
