'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.vegaAssetId) writer.bytes(1, obj.vegaAssetId, types.string);
  if (obj.sourceEthereumAddress)
    writer.bytes(2, obj.sourceEthereumAddress, types.string);
  if (obj.lifetimeLimits) writer.bytes(3, obj.lifetimeLimits, types.string);
  if (obj.withdrawThreshold) writer.bytes(4, obj.withdrawThreshold, types.string);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
