'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');
var decode$5 = require('../ERC20AssetList/decode.cjs');
var decode$4 = require('../ERC20AssetDelist/decode.cjs');
var decode$3 = require('../ERC20Deposit/decode.cjs');
var decode$2 = require('../ERC20Withdrawal/decode.cjs');
var decode$1 = require('../ERC20AssetLimitsUpdated/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$index = 0n;
  let field$block = 0n;
  let field$action = null;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$index = types.uint64(data);
        break

      case 2:
        field$block = types.uint64(data);
        break

      case 1001:
        field$action = { assetList: decode$5.decode(data) };
        break

      case 1002:
        field$action = { assetDelist: decode$4.decode(data) };
        break

      case 1003:
        field$action = { deposit: decode$3.decode(data) };
        break

      case 1004:
        field$action = { withdrawal: decode$2.decode(data) };
        break

      case 1005:
        field$action = {
          assetLimitsUpdated: decode$1.decode(data)
        };
        break

      case 1006:
        field$action = { bridgeStopped: types.bool(data) };
        break

      case 1007:
        field$action = { bridgeResumed: types.bool(data) };
        break
    }
  }
  return { index: field$index, block: field$block, action: field$action }
}

exports.decode = decode;
