'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.newThreshold) writer.varint(1, obj.newThreshold, types.uint32);
  if (obj.nonce) writer.bytes(2, obj.nonce, types.string);
  if (obj.blockTime) writer.varint(3, obj.blockTime, types.int64);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
