/// autogenerated by protoc-plugin-js
const assert = require('nanoassert')
const { enumerable } = require('protobuf-codec/encode/types')
const { enumerable: decodeEnumerable } = require('protobuf-codec/decode/types')

const SIZE_OVERRIDE_SETTING_UNSPECIFIED = 0
const SIZE_OVERRIDE_SETTING_NONE = 1
const SIZE_OVERRIDE_SETTING_POSITION = 2

const enumValues = new Map([
  [0, 'SIZE_OVERRIDE_SETTING_UNSPECIFIED'],
  [1, 'SIZE_OVERRIDE_SETTING_NONE'],
  [2, 'SIZE_OVERRIDE_SETTING_POSITION']
])
const enumNames = new Map([
  ['SIZE_OVERRIDE_SETTING_UNSPECIFIED', 0],
  ['SIZE_OVERRIDE_SETTING_NONE', 1],
  ['SIZE_OVERRIDE_SETTING_POSITION', 2]
])

function encode(value, buf, byteOffset = 0) {
  if (typeof value === 'string') return encode(parse(value), buf, byteOffset)
  if (value == null)
    throw new Error('Invalid SizeOverrideSetting value (' + value + ')')

  return enumerable.encode(value, buf, byteOffset)
}

function decode(varint) {
  const int = decodeEnumerable(varint)

  return stringify(int) ?? int
}

function encodingLength(value) {
  if (typeof value === 'string') return encodingLength(parse(value))
  assert(value != null, 'Invalid SizeOverrideSetting value (' + value + ')')

  if (0 <= value && value <= 2) return 1

  // enumerable max value in case of unknown value
  return 5
}

/**
 * Convert an enum value to it's human readable name.
 * Returns undefined on an unknown value.
 */
function stringify(int) {
  return enumValues.get(int)
}

/**
 * Convert an enum string names to it's machine integer value.
 * Returns undefined on an unknown name.
 */
function parse(str) {
  return enumNames.get(str)
}

module.exports = {
  encode,
  decode,
  encodingLength,
  stringify,
  parse,
  SIZE_OVERRIDE_SETTING_UNSPECIFIED,
  SIZE_OVERRIDE_SETTING_NONE,
  SIZE_OVERRIDE_SETTING_POSITION
}
