/// autogenerated by protoc-plugin-js
import type { CancelTransferConfiguration } from '../CancelTransferConfiguration'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): CancelTransferConfiguration
