/// autogenerated by protoc-plugin-js
import type { DataSourceDefinitionExternal } from '../DataSourceDefinitionExternal'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): DataSourceDefinitionExternal
