/// autogenerated by protoc-plugin-js
import type { Erc20WithdrawExt } from '../Erc20WithdrawExt'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): Erc20WithdrawExt
