/// autogenerated by protoc-plugin-js
import type { UpdateFutureProduct } from '../UpdateFutureProduct'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): UpdateFutureProduct
