/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { UpdateFutureProduct } from '../UpdateFutureProduct'
export function encode(
  obj?: PartialDeep<UpdateFutureProduct>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
