/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { string } = require('protobuf-codec/decode/types')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$threshold = ''
  let field$duration = ''
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$threshold = string(data)
        break

      case 2:
        field$duration = string(data)
        break
    }
  }
  return { threshold: field$threshold, duration: field$duration }
}
