/// autogenerated by protoc-plugin-js
import type { ConcentratedLiquidityParameters } from '../ConcentratedLiquidityParameters'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): ConcentratedLiquidityParameters
