'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');
var encode$1 = require('../KeyValueBundle/encode.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.stateVarId) writer.bytes(1, obj.stateVarId, types.string);
  if (obj.eventId) writer.bytes(2, obj.eventId, types.string);
  if (obj.kvb?.length)
    obj.kvb.forEach((v) => writer.bytes(3, encode$1.encode(v)));

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
