/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { SuccessorConfiguration } from '../SuccessorConfiguration'
export function encode(
  obj?: PartialDeep<SuccessorConfiguration>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
