/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { string, bool } = require('protobuf-codec/encode/types')
const _vega_commands_v1_UpdateReferralSet_Team = require('./Team/encode.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.id) writer.bytes(1, obj.id, string)
  if (obj.isTeam) writer.varint(2, obj.isTeam, bool)
  if (obj.team)
    writer.bytes(3, _vega_commands_v1_UpdateReferralSet_Team.encode(obj.team))

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
