/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { NewTransfer } from '../NewTransfer'
export function encode(
  obj?: PartialDeep<NewTransfer>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
