/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { ExternalData } from '../ExternalData'
export function encode(
  obj?: PartialDeep<ExternalData>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
