/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { LiquidityProvisionV2 } from '../LiquidityProvisionV2'
export function encode(
  obj?: PartialDeep<LiquidityProvisionV2>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
