'use strict';

var Writer = require('protobuf-codec/encode/writer');
var encode$1 = require('../DataSourceSpecConfiguration/encode.cjs');
var encode$2 = require('../EthCallSpec/encode.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.source_type?.oracle ?? obj.oracle)
    writer.bytes(
      1,
      encode$1.encode(
        obj.source_type?.oracle ?? obj.oracle
      )
    );
  if (obj.source_type?.ethCall ?? obj.ethCall)
    writer.bytes(
      2,
      encode$2.encode(obj.source_type?.ethCall ?? obj.ethCall)
    );

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
