/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { Transfer } from '../Transfer'
export function encode(
  obj?: PartialDeep<Transfer>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
