/// autogenerated by protoc-plugin-js
import type { LiquidityProvision } from '../LiquidityProvision'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): LiquidityProvision
