/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { LiquidityProvision } from '../LiquidityProvision'
export function encode(
  obj?: PartialDeep<LiquidityProvision>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
