/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { PostTransferBalance } from '../PostTransferBalance'
export function encode(
  obj?: PartialDeep<PostTransferBalance>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
