'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');
var OracleSource = require('./OracleSource.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$source = 0;
  let field$payload = new Uint8Array(0);
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$source =
          OracleSource.decode(data);
        break

      case 2:
        field$payload = types.bytes(data);
        break
    }
  }
  return { source: field$source, payload: field$payload }
}

exports.decode = decode;
