/// autogenerated by protoc-plugin-js
import type { OrderSubmission } from '../OrderSubmission'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): OrderSubmission
