/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { OrderSubmission } from '../OrderSubmission'
export function encode(
  obj?: PartialDeep<OrderSubmission>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
