/// autogenerated by protoc-plugin-js
import type { ERC20MultiSigEvent } from '../ERC20MultiSigEvent'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): ERC20MultiSigEvent
