'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$party = '';
  let field$nodeId = '';
  let field$amount = '';
  let field$epochSeq = '';
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$party = types.string(data);
        break

      case 2:
        field$nodeId = types.string(data);
        break

      case 3:
        field$amount = types.string(data);
        break

      case 4:
        field$epochSeq = types.string(data);
        break
    }
  }
  return {
    party: field$party,
    nodeId: field$nodeId,
    amount: field$amount,
    epochSeq: field$epochSeq
  }
}

exports.decode = decode;
