'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$makerFee = '';
  let field$infrastructureFee = '';
  let field$liquidityFee = '';
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$makerFee = types.string(data);
        break

      case 2:
        field$infrastructureFee = types.string(data);
        break

      case 3:
        field$liquidityFee = types.string(data);
        break
    }
  }
  return {
    makerFee: field$makerFee,
    infrastructureFee: field$infrastructureFee,
    liquidityFee: field$liquidityFee
  }
}

exports.decode = decode;
