/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { Fee } from '../Fee'
export function encode(
  obj?: PartialDeep<Fee>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
