/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { UpdateInstrumentConfiguration } from '../UpdateInstrumentConfiguration'
export function encode(
  obj?: PartialDeep<UpdateInstrumentConfiguration>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
