/// autogenerated by protoc-plugin-js
import type { OrderAmendment } from '../OrderAmendment'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): OrderAmendment
