/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { string, int64, uint64 } = require('protobuf-codec/encode/types')
const _vega_Order_TimeInForce = require('./../../../Order/TimeInForce.js')
const _vega_PeggedReference = require('./../../../PeggedReference.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.orderId) writer.bytes(1, obj.orderId, string)
  if (obj.marketId) writer.bytes(2, obj.marketId, string)
  if (obj.price) writer.bytes(3, obj.price, string)
  if (obj.sizeDelta) writer.varint(4, obj.sizeDelta, int64)
  if (obj.expiresAt) writer.varint(5, obj.expiresAt, int64)
  if (obj.timeInForce)
    writer.varint(6, obj.timeInForce, _vega_Order_TimeInForce)
  if (obj.peggedOffset) writer.bytes(7, obj.peggedOffset, string)
  if (obj.peggedReference)
    writer.varint(8, obj.peggedReference, _vega_PeggedReference)
  if (obj.size) writer.varint(9, obj.size, uint64)

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
