/// autogenerated by protoc-plugin-js
import type { UpdateSpotMarketConfiguration } from '../UpdateSpotMarketConfiguration'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): UpdateSpotMarketConfiguration
