/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { UpdatePerpetualProduct } from '../UpdatePerpetualProduct'
export function encode(
  obj?: PartialDeep<UpdatePerpetualProduct>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
