/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { StateVariableProposal } from '../StateVariableProposal'
export function encode(
  obj?: PartialDeep<StateVariableProposal>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
