/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { EpochRewardSummary } from '../EpochRewardSummary'
export function encode(
  obj?: PartialDeep<EpochRewardSummary>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
