/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { CreateTeam } from '../CreateTeam'
export function encode(
  obj?: PartialDeep<CreateTeam>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
