/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { SizeOverrideValue } from '../SizeOverrideValue'
export function encode(
  obj?: PartialDeep<SizeOverrideValue>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
