'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$total = 0;
  let field$inactive = 0;
  const field$promoted = [];
  const field$demoted = [];
  let field$maximum = null;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$total = types.uint32(data);
        break

      case 2:
        field$inactive = types.uint32(data);
        break

      case 3:
        field$promoted.push(types.string(data));
        break

      case 4:
        field$demoted.push(types.string(data));
        break

      case 5:
        field$maximum = types.uint32(data);
        break
    }
  }
  return {
    total: field$total,
    inactive: field$inactive,
    promoted: field$promoted,
    demoted: field$demoted,
    maximum: field$maximum
  }
}

exports.decode = decode;
