'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.total) writer.varint(1, obj.total, types.uint32);
  if (obj.inactive) writer.varint(2, obj.inactive, types.uint32);
  if (obj.promoted?.length)
    obj.promoted.forEach((v) => writer.bytes(3, v, types.string));
  if (obj.demoted?.length)
    obj.demoted.forEach((v) => writer.bytes(4, v, types.string));
  if (obj.maximum) writer.varint(5, obj.maximum, types.uint32);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
