/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { DataSourceSpecConfiguration } from '../DataSourceSpecConfiguration'
export function encode(
  obj?: PartialDeep<DataSourceSpecConfiguration>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
