/// autogenerated by protoc-plugin-js
import type { SpecBindingForCompositePrice } from '../SpecBindingForCompositePrice'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): SpecBindingForCompositePrice
