/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { VolumeBenefitTier } from '../VolumeBenefitTier'
export function encode(
  obj?: PartialDeep<VolumeBenefitTier>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
