/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { double } = require('protobuf-codec/decode/types')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$searchLevel = 0
  let field$initialMargin = 0
  let field$collateralRelease = 0
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$searchLevel = double(data)
        break

      case 2:
        field$initialMargin = double(data)
        break

      case 3:
        field$collateralRelease = double(data)
        break
    }
  }
  return {
    searchLevel: field$searchLevel,
    initialMargin: field$initialMargin,
    collateralRelease: field$collateralRelease
  }
}
