/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { ScalingFactors } from '../ScalingFactors'
export function encode(
  obj?: PartialDeep<ScalingFactors>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
