/// autogenerated by protoc-plugin-js
import type { VolumeRebateBenefitTier } from '../VolumeRebateBenefitTier'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): VolumeRebateBenefitTier
