/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { string, uint64 } = require('protobuf-codec/decode/types')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$minimumPartyMakerVolumeFraction = ''
  let field$additionalMakerRebate = ''
  let field$tierNumber = null
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$minimumPartyMakerVolumeFraction = string(data)
        break

      case 2:
        field$additionalMakerRebate = string(data)
        break

      case 3:
        field$tierNumber = uint64(data)
        break
    }
  }
  return {
    minimumPartyMakerVolumeFraction: field$minimumPartyMakerVolumeFraction,
    additionalMakerRebate: field$additionalMakerRebate,
    tierNumber: field$tierNumber
  }
}
