/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { VolumeRebateBenefitTier } from '../VolumeRebateBenefitTier'
export function encode(
  obj?: PartialDeep<VolumeRebateBenefitTier>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
