'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$oldSigner = '';
  let field$nonce = '';
  let field$blockTime = 0n;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$oldSigner = types.string(data);
        break

      case 2:
        field$nonce = types.string(data);
        break

      case 3:
        field$blockTime = types.int64(data);
        break
    }
  }
  return {
    oldSigner: field$oldSigner,
    nonce: field$nonce,
    blockTime: field$blockTime
  }
}

exports.decode = decode;
