/// autogenerated by protoc-plugin-js
const assert = require('nanoassert')
const { enumerable } = require('protobuf-codec/encode/types')
const { enumerable: decodeEnumerable } = require('protobuf-codec/decode/types')

const TRADING_MODE_UNSPECIFIED = 0
const TRADING_MODE_CONTINUOUS = 1
const TRADING_MODE_BATCH_AUCTION = 2
const TRADING_MODE_OPENING_AUCTION = 3
const TRADING_MODE_MONITORING_AUCTION = 4
const TRADING_MODE_NO_TRADING = 5
const TRADING_MODE_SUSPENDED_VIA_GOVERNANCE = 6
const TRADING_MODE_LONG_BLOCK_AUCTION = 7

const enumValues = new Map([
  [0, 'TRADING_MODE_UNSPECIFIED'],
  [1, 'TRADING_MODE_CONTINUOUS'],
  [2, 'TRADING_MODE_BATCH_AUCTION'],
  [3, 'TRADING_MODE_OPENING_AUCTION'],
  [4, 'TRADING_MODE_MONITORING_AUCTION'],
  [5, 'TRADING_MODE_NO_TRADING'],
  [6, 'TRADING_MODE_SUSPENDED_VIA_GOVERNANCE'],
  [7, 'TRADING_MODE_LONG_BLOCK_AUCTION']
])
const enumNames = new Map([
  ['TRADING_MODE_UNSPECIFIED', 0],
  ['TRADING_MODE_CONTINUOUS', 1],
  ['TRADING_MODE_BATCH_AUCTION', 2],
  ['TRADING_MODE_OPENING_AUCTION', 3],
  ['TRADING_MODE_MONITORING_AUCTION', 4],
  ['TRADING_MODE_NO_TRADING', 5],
  ['TRADING_MODE_SUSPENDED_VIA_GOVERNANCE', 6],
  ['TRADING_MODE_LONG_BLOCK_AUCTION', 7]
])

function encode(value, buf, byteOffset = 0) {
  if (typeof value === 'string') return encode(parse(value), buf, byteOffset)
  if (value == null)
    throw new Error('Invalid TradingMode value (' + value + ')')

  return enumerable.encode(value, buf, byteOffset)
}

function decode(varint) {
  const int = decodeEnumerable(varint)

  return stringify(int) ?? int
}

function encodingLength(value) {
  if (typeof value === 'string') return encodingLength(parse(value))
  assert(value != null, 'Invalid TradingMode value (' + value + ')')

  if (0 <= value && value <= 7) return 1

  // enumerable max value in case of unknown value
  return 5
}

/**
 * Convert an enum value to it's human readable name.
 * Returns undefined on an unknown value.
 */
function stringify(int) {
  return enumValues.get(int)
}

/**
 * Convert an enum string names to it's machine integer value.
 * Returns undefined on an unknown name.
 */
function parse(str) {
  return enumNames.get(str)
}

module.exports = {
  encode,
  decode,
  encodingLength,
  stringify,
  parse,
  TRADING_MODE_UNSPECIFIED,
  TRADING_MODE_CONTINUOUS,
  TRADING_MODE_BATCH_AUCTION,
  TRADING_MODE_OPENING_AUCTION,
  TRADING_MODE_MONITORING_AUCTION,
  TRADING_MODE_NO_TRADING,
  TRADING_MODE_SUSPENDED_VIA_GOVERNANCE,
  TRADING_MODE_LONG_BLOCK_AUCTION
}
