/// autogenerated by protoc-plugin-js
import type { InternalTimeTrigger } from '../InternalTimeTrigger'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): InternalTimeTrigger
