/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { InternalTimeTrigger } from '../InternalTimeTrigger'
export function encode(
  obj?: PartialDeep<InternalTimeTrigger>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
