/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { PriceMonitoringParameters } from '../PriceMonitoringParameters'
export function encode(
  obj?: PartialDeep<PriceMonitoringParameters>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
