/// autogenerated by protoc-plugin-js

export * from './InternalTimeTrigger/encode.js'
export * from './InternalTimeTrigger/decode.js'

export type InternalTimeTrigger = {
  initial: bigint | null
  every: bigint
}
