/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { Perpetual } from '../Perpetual'
export function encode(
  obj?: PartialDeep<Perpetual>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
