/// autogenerated by protoc-plugin-js
import type { NewSpotMarketConfiguration } from '../NewSpotMarketConfiguration'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): NewSpotMarketConfiguration
