/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { Signer } from '../Signer'
export function encode(
  obj?: PartialDeep<Signer>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
