/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { string } = require('protobuf-codec/decode/types')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$assetId = ''
  let field$partyId = ''
  let field$amount = ''
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$assetId = string(data)
        break

      case 2:
        field$partyId = string(data)
        break

      case 3:
        field$amount = string(data)
        break
    }
  }
  return {
    assetId: field$assetId,
    partyId: field$partyId,
    amount: field$amount
  }
}
