/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { string } = require('protobuf-codec/encode/types')
const _vega_commands_v1_UndelegateSubmission_Method = require('./Method.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.nodeId) writer.bytes(1, obj.nodeId, string)
  if (obj.amount) writer.bytes(2, obj.amount, string)
  if (obj.method)
    writer.varint(3, obj.method, _vega_commands_v1_UndelegateSubmission_Method)

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
