/// autogenerated by protoc-plugin-js
import type { NewProtocolAutomatedPurchase } from '../NewProtocolAutomatedPurchase'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): NewProtocolAutomatedPurchase
