/// autogenerated by protoc-plugin-js
import type { PerMarketEquityLikeShareWeightEntry } from '../PerMarketEquityLikeShareWeightEntry'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): PerMarketEquityLikeShareWeightEntry
