/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { PerMarketEquityLikeShareWeightEntry } from '../PerMarketEquityLikeShareWeightEntry'
export function encode(
  obj?: PartialDeep<PerMarketEquityLikeShareWeightEntry>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
