'use strict';

var encode = require('./ListValue/encode.cjs');
var decode = require('./ListValue/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
