/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { VestingBenefitTiers } from '../VestingBenefitTiers'
export function encode(
  obj?: PartialDeep<VestingBenefitTiers>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
