'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$baseAsset = '';
  let field$quoteAsset = '';
  let field$name = '';
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$baseAsset = types.string(data);
        break

      case 2:
        field$quoteAsset = types.string(data);
        break

      case 3:
        field$name = types.string(data);
        break
    }
  }
  return {
    baseAsset: field$baseAsset,
    quoteAsset: field$quoteAsset,
    name: field$name
  }
}

exports.decode = decode;
