/// autogenerated by protoc-plugin-js
import type { UpdateReferralProgram } from '../UpdateReferralProgram'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): UpdateReferralProgram
