/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { UpdateReferralProgram } from '../UpdateReferralProgram'
export function encode(
  obj?: PartialDeep<UpdateReferralProgram>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
