/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { YesPartyEntry } from '../YesPartyEntry'
export function encode(
  obj?: PartialDeep<YesPartyEntry>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
