'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');
var AccountType = require('../../../AccountType.cjs');
var decode$2 = require('../OneOffTransfer/decode.cjs');
var decode$1 = require('../RecurringTransfer/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$fromAccountType = 0;
  let field$to = '';
  let field$toAccountType = 0;
  let field$asset = '';
  let field$amount = '';
  let field$reference = '';
  let field$kind = null;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$fromAccountType = AccountType.decode(data);
        break

      case 2:
        field$to = types.string(data);
        break

      case 3:
        field$toAccountType = AccountType.decode(data);
        break

      case 4:
        field$asset = types.string(data);
        break

      case 5:
        field$amount = types.string(data);
        break

      case 6:
        field$reference = types.string(data);
        break

      case 101:
        field$kind = { oneOff: decode$2.decode(data) };
        break

      case 102:
        field$kind = {
          recurring: decode$1.decode(data)
        };
        break
    }
  }
  return {
    fromAccountType: field$fromAccountType,
    to: field$to,
    toAccountType: field$toAccountType,
    asset: field$asset,
    amount: field$amount,
    reference: field$reference,
    kind: field$kind
  }
}

exports.decode = decode;
