/// autogenerated by protoc-plugin-js
import type { DataSourceSpecToPerpetualBinding } from '../DataSourceSpecToPerpetualBinding'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): DataSourceSpecToPerpetualBinding
