/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { DataSourceSpecToPerpetualBinding } from '../DataSourceSpecToPerpetualBinding'
export function encode(
  obj?: PartialDeep<DataSourceSpecToPerpetualBinding>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
