/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { InputData } from '../InputData'
export function encode(
  obj?: PartialDeep<InputData>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
