'use strict';

var reader = require('protobuf-codec/decode/reader');
var decode$1 = require('../StopOrderSetup/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$risesAbove = null;
  let field$fallsBelow = null;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$risesAbove = decode$1.decode(data);
        break

      case 2:
        field$fallsBelow = decode$1.decode(data);
        break
    }
  }
  return { risesAbove: field$risesAbove, fallsBelow: field$fallsBelow }
}

exports.decode = decode;
