/// autogenerated by protoc-plugin-js
import type { LiquidityProviderFeeShare } from '../LiquidityProviderFeeShare'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): LiquidityProviderFeeShare
