/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { Signature } from '../Signature'
export function encode(
  obj?: PartialDeep<Signature>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
