/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { ProductData } from '../ProductData'
export function encode(
  obj?: PartialDeep<ProductData>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
