'use strict';

var Writer = require('protobuf-codec/encode/writer');
var encode$1 = require('../DataSourceDefinitionInternal/encode.cjs');
var encode$2 = require('../DataSourceDefinitionExternal/encode.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.source_type?.internal ?? obj.internal)
    writer.bytes(
      1,
      encode$1.encode(
        obj.source_type?.internal ?? obj.internal
      )
    );
  if (obj.source_type?.external ?? obj.external)
    writer.bytes(
      2,
      encode$2.encode(
        obj.source_type?.external ?? obj.external
      )
    );

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
