/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { PriceMonitoringBounds } from '../PriceMonitoringBounds'
export function encode(
  obj?: PartialDeep<PriceMonitoringBounds>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
