'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');
var Value = require('./Value.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.partyId) writer.bytes(1, obj.partyId, types.string);
  if (obj.value) writer.varint(2, obj.value, Value);
  if (obj.proposalId) writer.bytes(3, obj.proposalId, types.string);
  if (obj.timestamp) writer.varint(4, obj.timestamp, types.int64);
  if (obj.totalGovernanceTokenBalance)
    writer.bytes(5, obj.totalGovernanceTokenBalance, types.string);
  if (obj.totalGovernanceTokenWeight)
    writer.bytes(6, obj.totalGovernanceTokenWeight, types.string);
  if (obj.totalEquityLikeShareWeight)
    writer.bytes(7, obj.totalEquityLikeShareWeight, types.string);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
