/// autogenerated by protoc-plugin-js
import type { ApplyReferralCode } from '../ApplyReferralCode'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): ApplyReferralCode
