'use strict';

var encode = require('./AnnounceNode/encode.cjs');
var decode = require('./AnnounceNode/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
