'use strict';

var encode = require('./BatchMarketInstructions/encode.cjs');
var decode = require('./BatchMarketInstructions/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
