'use strict';

var encode = require('./ChainEvent/encode.cjs');
var decode = require('./ChainEvent/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
