'use strict';

var encode = require('./DelegateSubmission/encode.cjs');
var decode = require('./DelegateSubmission/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
