'use strict';

var encode = require('./LiquidityProvisionCancellation/encode.cjs');
var decode = require('./LiquidityProvisionCancellation/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
