'use strict';

var assert = require('nanoassert');
var types = require('protobuf-codec/encode/types');
var types$1 = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

const NODE_SIGNATURE_KIND_UNSPECIFIED = 0;
const NODE_SIGNATURE_KIND_ASSET_NEW = 1;
const NODE_SIGNATURE_KIND_ASSET_WITHDRAWAL = 2;
const NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_ADDED = 3;
const NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_REMOVED = 4;
const NODE_SIGNATURE_KIND_ASSET_UPDATE = 5;

const enumValues = new Map([
  [0, 'NODE_SIGNATURE_KIND_UNSPECIFIED'],
  [1, 'NODE_SIGNATURE_KIND_ASSET_NEW'],
  [2, 'NODE_SIGNATURE_KIND_ASSET_WITHDRAWAL'],
  [3, 'NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_ADDED'],
  [4, 'NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_REMOVED'],
  [5, 'NODE_SIGNATURE_KIND_ASSET_UPDATE']
]);
const enumNames = new Map([
  ['NODE_SIGNATURE_KIND_UNSPECIFIED', 0],
  ['NODE_SIGNATURE_KIND_ASSET_NEW', 1],
  ['NODE_SIGNATURE_KIND_ASSET_WITHDRAWAL', 2],
  ['NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_ADDED', 3],
  ['NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_REMOVED', 4],
  ['NODE_SIGNATURE_KIND_ASSET_UPDATE', 5]
]);

function encode(value, buf, byteOffset = 0) {
  if (typeof value === 'string') return encode(parse(value), buf, byteOffset)
  if (value == null)
    throw new Error('Invalid NodeSignatureKind value (' + value + ')')

  return types.enumerable.encode(value, buf, byteOffset)
}

function decode(varint) {
  const int = types$1.enumerable(varint);

  return stringify(int) ?? int
}

function encodingLength(value) {
  if (typeof value === 'string') return encodingLength(parse(value))
  assert(value != null, 'Invalid NodeSignatureKind value (' + value + ')');

  if (0 <= value && value <= 5) return 1

  // enumerable max value in case of unknown value
  return 5
}

/**
 * Convert an enum value to it's human readable name.
 * Returns undefined on an unknown value.
 */
function stringify(int) {
  return enumValues.get(int)
}

/**
 * Convert an enum string names to it's machine integer value.
 * Returns undefined on an unknown name.
 */
function parse(str) {
  return enumNames.get(str)
}

exports.NODE_SIGNATURE_KIND_ASSET_NEW = NODE_SIGNATURE_KIND_ASSET_NEW;
exports.NODE_SIGNATURE_KIND_ASSET_UPDATE = NODE_SIGNATURE_KIND_ASSET_UPDATE;
exports.NODE_SIGNATURE_KIND_ASSET_WITHDRAWAL = NODE_SIGNATURE_KIND_ASSET_WITHDRAWAL;
exports.NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_ADDED = NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_ADDED;
exports.NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_REMOVED = NODE_SIGNATURE_KIND_ERC20_MULTISIG_SIGNER_REMOVED;
exports.NODE_SIGNATURE_KIND_UNSPECIFIED = NODE_SIGNATURE_KIND_UNSPECIFIED;
exports.decode = decode;
exports.encode = encode;
exports.encodingLength = encodingLength;
exports.parse = parse;
exports.stringify = stringify;
