'use strict';

var encode = require('./NodeSignature/encode.cjs');
var decode = require('./NodeSignature/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
