'use strict';

var encode = require('./OrderCancellation/encode.cjs');
var decode = require('./OrderCancellation/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
