'use strict';

var encode = require('./ProofOfWork/encode.cjs');
var decode = require('./ProofOfWork/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
