'use strict';

var encode = require('./ProtocolUpgradeProposal/encode.cjs');
var decode = require('./ProtocolUpgradeProposal/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
