'use strict';

var encode = require('./Signature/encode.cjs');
var decode = require('./Signature/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
