'use strict';

var encode = require('./StopOrdersSubmission/encode.cjs');
var decode = require('./StopOrdersSubmission/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
