'use strict';

var encode = require('./Transaction/encode.cjs');
var decode = require('./Transaction/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
