'use strict';

var encode = require('./UndelegateSubmission/encode.cjs');
var decode = require('./UndelegateSubmission/decode.cjs');
var Method = require('./UndelegateSubmission/Method.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
exports.Method = Method;
