'use strict';

var encode = require('./VoteSubmission/encode.cjs');
var decode = require('./VoteSubmission/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
