'use strict';

var encode = require('./WithdrawSubmission/encode.cjs');
var decode = require('./WithdrawSubmission/decode.cjs');

/// autogenerated by protoc-plugin-js

exports.encode = encode.encode;
exports.decode = decode.decode;
