'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');
var decode$1 = require('../UpdateFutureProduct/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$code = '';
  let field$product = null;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$code = types.string(data);
        break

      case 100:
        field$product = { future: decode$1.decode(data) };
        break
    }
  }
  return { code: field$code, product: field$product }
}

exports.decode = decode;
