/// autogenerated by protoc-plugin-js
import type { LiquidityProvisionAmendment } from '../LiquidityProvisionAmendment'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): LiquidityProvisionAmendment
