/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { RiskFactorOverride } from '../RiskFactorOverride'
export function encode(
  obj?: PartialDeep<RiskFactorOverride>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
