/// autogenerated by protoc-plugin-js
import type { NewProtocolAutomatedPurchaseChanges } from '../NewProtocolAutomatedPurchaseChanges'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): NewProtocolAutomatedPurchaseChanges
