/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { NewProtocolAutomatedPurchaseChanges } from '../NewProtocolAutomatedPurchaseChanges'
export function encode(
  obj?: PartialDeep<NewProtocolAutomatedPurchaseChanges>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
