/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { string } = require('protobuf-codec/decode/types')
const _vega_commands_v1_CancelAMM_Method = require('./Method.js')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$marketId = ''
  let field$method = _vega_commands_v1_CancelAMM_Method.decode(0)
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$marketId = string(data)
        break

      case 2:
        field$method = _vega_commands_v1_CancelAMM_Method.decode(data)
        break
    }
  }
  return { marketId: field$marketId, method: field$method }
}
