/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { bool, int64 } = require('protobuf-codec/encode/types')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.canProposeMarket) writer.varint(1, obj.canProposeMarket, bool)
  if (obj.canProposeAsset) writer.varint(2, obj.canProposeAsset, bool)
  if (obj.proposeMarketEnabled) writer.varint(4, obj.proposeMarketEnabled, bool)
  if (obj.proposeAssetEnabled) writer.varint(5, obj.proposeAssetEnabled, bool)
  if (obj.genesisLoaded) writer.varint(7, obj.genesisLoaded, bool)
  if (obj.proposeMarketEnabledFrom)
    writer.varint(8, obj.proposeMarketEnabledFrom, int64)
  if (obj.proposeAssetEnabledFrom)
    writer.varint(9, obj.proposeAssetEnabledFrom, int64)
  if (obj.canProposeSpotMarket)
    writer.varint(10, obj.canProposeSpotMarket, bool)
  if (obj.canProposePerpetualMarket)
    writer.varint(11, obj.canProposePerpetualMarket, bool)
  if (obj.canUseAmm) writer.varint(12, obj.canUseAmm, bool)

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
