/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { string, bool } = require('protobuf-codec/decode/types')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$name = null
  let field$teamUrl = null
  let field$avatarUrl = null
  let field$closed = null
  const field$allowList = []
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 10:
        field$name = string(data)
        break

      case 11:
        field$teamUrl = string(data)
        break

      case 12:
        field$avatarUrl = string(data)
        break

      case 13:
        field$closed = bool(data)
        break

      case 14:
        field$allowList.push(string(data))
        break
    }
  }
  return {
    name: field$name,
    teamUrl: field$teamUrl,
    avatarUrl: field$avatarUrl,
    closed: field$closed,
    allowList: field$allowList
  }
}
