/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { string } = require('protobuf-codec/decode/types')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$contractAddress = ''
  let field$lifetimeLimit = ''
  let field$withdrawThreshold = ''
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$contractAddress = string(data)
        break

      case 2:
        field$lifetimeLimit = string(data)
        break

      case 3:
        field$withdrawThreshold = string(data)
        break
    }
  }
  return {
    contractAddress: field$contractAddress,
    lifetimeLimit: field$lifetimeLimit,
    withdrawThreshold: field$withdrawThreshold
  }
}
