'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$ethereumAddress = '';
  let field$vegaPublicKey = '';
  let field$amount = '';
  let field$blockTime = 0n;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$ethereumAddress = types.string(data);
        break

      case 2:
        field$vegaPublicKey = types.string(data);
        break

      case 3:
        field$amount = types.string(data);
        break

      case 4:
        field$blockTime = types.int64(data);
        break
    }
  }
  return {
    ethereumAddress: field$ethereumAddress,
    vegaPublicKey: field$vegaPublicKey,
    amount: field$amount,
    blockTime: field$blockTime
  }
}

exports.decode = decode;
