'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.ethereumAddress) writer.bytes(1, obj.ethereumAddress, types.string);
  if (obj.vegaPublicKey) writer.bytes(2, obj.vegaPublicKey, types.string);
  if (obj.amount) writer.bytes(3, obj.amount, types.string);
  if (obj.blockTime) writer.varint(4, obj.blockTime, types.int64);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
