'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.total) writer.varint(1, obj.total, types.int32);
  if (obj.offline) writer.varint(2, obj.offline, types.int32);
  if (obj.online) writer.varint(3, obj.online, types.int32);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
