'use strict';

var reader = require('protobuf-codec/decode/reader');
var decode$1 = require('../Value/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  const field$values = [];
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$values.push(decode$1.decode(data));
        break
    }
  }
  return { values: field$values }
}

exports.decode = decode;
