'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$newPubKeyIndex = 0;
  let field$targetBlock = 0n;
  let field$newPubKey = '';
  let field$currentPubKeyHash = '';
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$newPubKeyIndex = types.uint32(data);
        break

      case 2:
        field$targetBlock = types.uint64(data);
        break

      case 3:
        field$newPubKey = types.string(data);
        break

      case 4:
        field$currentPubKeyHash = types.string(data);
        break
    }
  }
  return {
    newPubKeyIndex: field$newPubKeyIndex,
    targetBlock: field$targetBlock,
    newPubKey: field$newPubKey,
    currentPubKeyHash: field$currentPubKeyHash
  }
}

exports.decode = decode;
