/// autogenerated by protoc-plugin-js
import type { DataSourceDefinition } from '../DataSourceDefinition'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): DataSourceDefinition
