/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')

const _vega_DataSourceDefinitionInternal = require('./../DataSourceDefinitionInternal/encode.js')
const _vega_DataSourceDefinitionExternal = require('./../DataSourceDefinitionExternal/encode.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.source_type?.internal ?? obj.internal)
    writer.bytes(
      1,
      _vega_DataSourceDefinitionInternal.encode(
        obj.source_type?.internal ?? obj.internal
      )
    )
  if (obj.source_type?.external ?? obj.external)
    writer.bytes(
      2,
      _vega_DataSourceDefinitionExternal.encode(
        obj.source_type?.external ?? obj.external
      )
    )

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
