/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { AssetDetails } from '../AssetDetails'
export function encode(
  obj?: PartialDeep<AssetDetails>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
