/// autogenerated by protoc-plugin-js
import type { VolumeRebateProgram } from '../VolumeRebateProgram'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): VolumeRebateProgram
