/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { NodeData } from '../NodeData'
export function encode(
  obj?: PartialDeep<NodeData>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
