/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { int64, uint64 } = require('protobuf-codec/encode/types')
const _vega_VolumeRebateBenefitTier = require('./../VolumeRebateBenefitTier/encode.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.benefitTiers?.length)
    obj.benefitTiers.forEach((v) =>
      writer.bytes(1, _vega_VolumeRebateBenefitTier.encode(v))
    )
  if (obj.endOfProgramTimestamp)
    writer.varint(2, obj.endOfProgramTimestamp, int64)
  if (obj.windowLength) writer.varint(3, obj.windowLength, uint64)

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
