/// autogenerated by protoc-plugin-js
import type { LiquidityMonitoringParameters } from '../LiquidityMonitoringParameters'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): LiquidityMonitoringParameters
