'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');
var decode$1 = require('../LiquidityOrder/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$orderId = '';
  let field$liquidityOrder = {};
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$orderId = types.string(data);
        break

      case 2:
        field$liquidityOrder = decode$1.decode(data);
        break
    }
  }
  return { orderId: field$orderId, liquidityOrder: field$liquidityOrder }
}

exports.decode = decode;
