'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');
var encode$1 = require('../InstrumentConfiguration/encode.cjs');
var encode$2 = require('../PriceMonitoringParameters/encode.cjs');
var encode$3 = require('../LiquidityMonitoringParameters/encode.cjs');
var encode$5 = require('../SimpleModelParams/encode.cjs');
var encode$6 = require('../LogNormalRiskModel/encode.cjs');
var encode$4 = require('../SuccessorConfiguration/encode.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.instrument)
    writer.bytes(1, encode$1.encode(obj.instrument));
  if (obj.decimalPlaces) writer.varint(2, obj.decimalPlaces, types.uint64);
  if (obj.metadata?.length)
    obj.metadata.forEach((v) => writer.bytes(3, v, types.string));
  if (obj.priceMonitoringParameters)
    writer.bytes(
      4,
      encode$2.encode(obj.priceMonitoringParameters)
    );
  if (obj.liquidityMonitoringParameters)
    writer.bytes(
      5,
      encode$3.encode(
        obj.liquidityMonitoringParameters
      )
    );
  if (obj.positionDecimalPlaces)
    writer.varint(6, obj.positionDecimalPlaces, types.int64);
  if (obj.lpPriceRange) writer.bytes(8, obj.lpPriceRange, types.string);
  if (obj.linearSlippageFactor)
    writer.bytes(9, obj.linearSlippageFactor, types.string);
  if (obj.quadraticSlippageFactor)
    writer.bytes(10, obj.quadraticSlippageFactor, types.string);
  if (obj.successor)
    writer.bytes(11, encode$4.encode(obj.successor));

  if (obj.risk_parameters?.simple ?? obj.simple)
    writer.bytes(
      100,
      encode$5.encode(obj.risk_parameters?.simple ?? obj.simple)
    );
  if (obj.risk_parameters?.logNormal ?? obj.logNormal)
    writer.bytes(
      101,
      encode$6.encode(
        obj.risk_parameters?.logNormal ?? obj.logNormal
      )
    );

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
