/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { LiquidationStrategy } from '../LiquidationStrategy'
export function encode(
  obj?: PartialDeep<LiquidationStrategy>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
