/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')

const _vega_Order = require('./../Order/encode.js')
const _vega_Trade = require('./../Trade/encode.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.order) writer.bytes(1, _vega_Order.encode(obj.order))
  if (obj.trades?.length)
    obj.trades.forEach((v) => writer.bytes(2, _vega_Trade.encode(v)))
  if (obj.passiveOrdersAffected?.length)
    obj.passiveOrdersAffected.forEach((v) =>
      writer.bytes(3, _vega_Order.encode(v))
    )

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
