'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.baseAsset) writer.bytes(1, obj.baseAsset, types.string);
  if (obj.quoteAsset) writer.bytes(2, obj.quoteAsset, types.string);
  if (obj.name) writer.bytes(3, obj.name, types.string);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
