/// autogenerated by protoc-plugin-js
import type { BatchProposalSubmissionTerms } from '../BatchProposalSubmissionTerms'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): BatchProposalSubmissionTerms
