/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { BatchProposalSubmissionTerms } from '../BatchProposalSubmissionTerms'
export function encode(
  obj?: PartialDeep<BatchProposalSubmissionTerms>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
