'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');
var ExpiryStrategy = require('./ExpiryStrategy.cjs');
var TriggerDirection = require('./TriggerDirection.cjs');
var Status = require('./Status.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.id) writer.bytes(1, obj.id, types.string);
  if (obj.ocoLinkId) writer.bytes(2, obj.ocoLinkId, types.string);
  if (obj.expiresAt) writer.varint(3, obj.expiresAt, types.int64);
  if (obj.expiryStrategy)
    writer.varint(4, obj.expiryStrategy, ExpiryStrategy);
  if (obj.triggerDirection)
    writer.varint(5, obj.triggerDirection, TriggerDirection);
  if (obj.status) writer.varint(6, obj.status, Status);
  if (obj.createdAt) writer.varint(7, obj.createdAt, types.int64);
  if (obj.updatedAt) writer.varint(8, obj.updatedAt, types.int64);
  if (obj.orderId) writer.bytes(9, obj.orderId, types.string);
  if (obj.partyId) writer.bytes(10, obj.partyId, types.string);
  if (obj.marketId) writer.bytes(11, obj.marketId, types.string);

  if (obj.trigger?.price ?? obj.price)
    writer.bytes(100, obj.trigger?.price ?? obj.price, types.string);
  if (obj.trigger?.trailingPercentOffset ?? obj.trailingPercentOffset)
    writer.bytes(
      101,
      obj.trigger?.trailingPercentOffset ?? obj.trailingPercentOffset,
      types.string
    );

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
