'use strict';

var assert = require('nanoassert');
var types = require('protobuf-codec/encode/types');
var types$1 = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

const TRIGGER_DIRECTION_UNSPECIFIED = 0;
const TRIGGER_DIRECTION_RISES_ABOVE = 1;
const TRIGGER_DIRECTION_FALLS_BELOW = 2;

const enumValues = new Map([
  [0, 'TRIGGER_DIRECTION_UNSPECIFIED'],
  [1, 'TRIGGER_DIRECTION_RISES_ABOVE'],
  [2, 'TRIGGER_DIRECTION_FALLS_BELOW']
]);
const enumNames = new Map([
  ['TRIGGER_DIRECTION_UNSPECIFIED', 0],
  ['TRIGGER_DIRECTION_RISES_ABOVE', 1],
  ['TRIGGER_DIRECTION_FALLS_BELOW', 2]
]);

function encode(value, buf, byteOffset = 0) {
  if (typeof value === 'string') return encode(parse(value), buf, byteOffset)
  if (value == null)
    throw new Error('Invalid TriggerDirection value (' + value + ')')

  return types.enumerable.encode(value, buf, byteOffset)
}

function decode(varint) {
  const int = types$1.enumerable(varint);

  return stringify(int) ?? int
}

function encodingLength(value) {
  if (typeof value === 'string') return encodingLength(parse(value))
  assert(value != null, 'Invalid TriggerDirection value (' + value + ')');

  if (0 <= value && value <= 2) return 1

  // enumerable max value in case of unknown value
  return 5
}

/**
 * Convert an enum value to it's human readable name.
 * Returns undefined on an unknown value.
 */
function stringify(int) {
  return enumValues.get(int)
}

/**
 * Convert an enum string names to it's machine integer value.
 * Returns undefined on an unknown name.
 */
function parse(str) {
  return enumNames.get(str)
}

exports.TRIGGER_DIRECTION_FALLS_BELOW = TRIGGER_DIRECTION_FALLS_BELOW;
exports.TRIGGER_DIRECTION_RISES_ABOVE = TRIGGER_DIRECTION_RISES_ABOVE;
exports.TRIGGER_DIRECTION_UNSPECIFIED = TRIGGER_DIRECTION_UNSPECIFIED;
exports.decode = decode;
exports.encode = encode;
exports.encodingLength = encodingLength;
exports.parse = parse;
exports.stringify = stringify;
