/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')

const _vega_PriceMonitoringParameters = require('./../PriceMonitoringParameters/decode.js')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$parameters = {}
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$parameters = _vega_PriceMonitoringParameters.decode(data)
        break
    }
  }
  return { parameters: field$parameters }
}
