/// autogenerated by protoc-plugin-js
import type { PriceMonitoringSettings } from '../PriceMonitoringSettings'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): PriceMonitoringSettings
