/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')

const _vega_PriceMonitoringParameters = require('./../PriceMonitoringParameters/encode.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.parameters)
    writer.bytes(1, _vega_PriceMonitoringParameters.encode(obj.parameters))

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
