/// autogenerated by protoc-plugin-js
import type { DataSourceSpecConfigurationTimeTrigger } from '../DataSourceSpecConfigurationTimeTrigger'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): DataSourceSpecConfigurationTimeTrigger
