/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')

const _vega_data_v1_Condition = require('./../data/v1/Condition/decode.js')
const _vega_data_v1_InternalTimeTrigger = require('./../data/v1/InternalTimeTrigger/decode.js')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  const field$conditions = []
  const field$triggers = []
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$conditions.push(_vega_data_v1_Condition.decode(data))
        break

      case 2:
        field$triggers.push(_vega_data_v1_InternalTimeTrigger.decode(data))
        break
    }
  }
  return { conditions: field$conditions, triggers: field$triggers }
}
