/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { DataSourceSpecConfigurationTimeTrigger } from '../DataSourceSpecConfigurationTimeTrigger'
export function encode(
  obj?: PartialDeep<DataSourceSpecConfigurationTimeTrigger>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
