/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')

const _vega_Proposal = require('./../Proposal/encode.js')
const _vega_Vote = require('./../Vote/encode.js')
const _vega_GovernanceData_YesPartyEntry = require('./YesPartyEntry/encode.js')
const _vega_GovernanceData_NoPartyEntry = require('./NoPartyEntry/encode.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.proposal) writer.bytes(1, _vega_Proposal.encode(obj.proposal))
  if (obj.yes?.length)
    obj.yes.forEach((v) => writer.bytes(2, _vega_Vote.encode(v)))
  if (obj.no?.length)
    obj.no.forEach((v) => writer.bytes(3, _vega_Vote.encode(v)))
  if (obj.yesParty?.length)
    obj.yesParty.forEach((v) =>
      writer.bytes(4, _vega_GovernanceData_YesPartyEntry.encode(v))
    )
  if (obj.noParty?.length)
    obj.noParty.forEach((v) =>
      writer.bytes(5, _vega_GovernanceData_NoPartyEntry.encode(v))
    )

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
