'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$price = '';
  let field$numberOfOrders = 0n;
  let field$volume = 0n;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$price = types.string(data);
        break

      case 2:
        field$numberOfOrders = types.uint64(data);
        break

      case 3:
        field$volume = types.uint64(data);
        break
    }
  }
  return {
    price: field$price,
    numberOfOrders: field$numberOfOrders,
    volume: field$volume
  }
}

exports.decode = decode;
