'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.price) writer.bytes(1, obj.price, types.string);
  if (obj.numberOfOrders) writer.varint(2, obj.numberOfOrders, types.uint64);
  if (obj.volume) writer.varint(3, obj.volume, types.uint64);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
