/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { Metadata } from '../Metadata'
export function encode(
  obj?: PartialDeep<Metadata>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
