/// autogenerated by protoc-plugin-js
import type { UpdateVolumeRebateProgram } from '../UpdateVolumeRebateProgram'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): UpdateVolumeRebateProgram
