'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.maintenanceMargin) writer.bytes(1, obj.maintenanceMargin, types.string);
  if (obj.searchLevel) writer.bytes(2, obj.searchLevel, types.string);
  if (obj.initialMargin) writer.bytes(3, obj.initialMargin, types.string);
  if (obj.collateralReleaseLevel)
    writer.bytes(4, obj.collateralReleaseLevel, types.string);
  if (obj.partyId) writer.bytes(5, obj.partyId, types.string);
  if (obj.marketId) writer.bytes(6, obj.marketId, types.string);
  if (obj.asset) writer.bytes(7, obj.asset, types.string);
  if (obj.timestamp) writer.varint(8, obj.timestamp, types.int64);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
