/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { string, int64 } = require('protobuf-codec/encode/types')
const _vega_PositionStatus = require('./../PositionStatus.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.marketId) writer.bytes(1, obj.marketId, string)
  if (obj.partyId) writer.bytes(2, obj.partyId, string)
  if (obj.openVolume) writer.varint(3, obj.openVolume, int64)
  if (obj.realisedPnl) writer.bytes(4, obj.realisedPnl, string)
  if (obj.unrealisedPnl) writer.bytes(5, obj.unrealisedPnl, string)
  if (obj.averageEntryPrice) writer.bytes(6, obj.averageEntryPrice, string)
  if (obj.updatedAt) writer.varint(7, obj.updatedAt, int64)
  if (obj.lossSocialisationAmount)
    writer.bytes(8, obj.lossSocialisationAmount, string)
  if (obj.positionStatus)
    writer.varint(9, obj.positionStatus, _vega_PositionStatus)
  if (obj.takerFeesPaid) writer.bytes(10, obj.takerFeesPaid, string)
  if (obj.makerFeesReceived) writer.bytes(11, obj.makerFeesReceived, string)
  if (obj.feesPaid) writer.bytes(12, obj.feesPaid, string)
  if (obj.takerFeesPaidSince) writer.bytes(13, obj.takerFeesPaidSince, string)
  if (obj.makerFeesReceivedSince)
    writer.bytes(14, obj.makerFeesReceivedSince, string)
  if (obj.feesPaidSince) writer.bytes(15, obj.feesPaidSince, string)
  if (obj.fundingPaymentAmount)
    writer.bytes(16, obj.fundingPaymentAmount, string)
  if (obj.fundingPaymentAmountSince)
    writer.bytes(17, obj.fundingPaymentAmountSince, string)

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
