'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$specId = '';
  let field$blockHeight = 0n;
  let field$blockTime = 0n;
  let field$result = new Uint8Array(0);
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$specId = types.string(data);
        break

      case 2:
        field$blockHeight = types.uint64(data);
        break

      case 3:
        field$blockTime = types.uint64(data);
        break

      case 4:
        field$result = types.bytes(data);
        break
    }
  }
  return {
    specId: field$specId,
    blockHeight: field$blockHeight,
    blockTime: field$blockTime,
    result: field$result
  }
}

exports.decode = decode;
