/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { BuiltinAssetWithdrawal } from '../BuiltinAssetWithdrawal'
export function encode(
  obj?: PartialDeep<BuiltinAssetWithdrawal>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
