/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { Condition } from '../Condition'
export function encode(
  obj?: PartialDeep<Condition>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
