'use strict';

var reader = require('protobuf-codec/decode/reader');
var decode$1 = require('../Order/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$order = {};
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$order = decode$1.decode(data);
        break
    }
  }
  return { order: field$order }
}

exports.decode = decode;
