/// autogenerated by protoc-plugin-js
import type { UpdateMarketState } from '../UpdateMarketState'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): UpdateMarketState
