/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { UpdateMarketState } from '../UpdateMarketState'
export function encode(
  obj?: PartialDeep<UpdateMarketState>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
