'use strict';

var reader = require('protobuf-codec/decode/reader');
var decode$1 = require('../Erc20WithdrawExt/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$ext = null;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$ext = { erc20: decode$1.decode(data) };
        break
    }
  }
  return { ext: field$ext }
}

exports.decode = decode;
