/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { Trade } from '../Trade'
export function encode(
  obj?: PartialDeep<Trade>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
