/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { LiquiditySLAParameters } from '../LiquiditySLAParameters'
export function encode(
  obj?: PartialDeep<LiquiditySLAParameters>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
