/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { string, uint32 } = require('protobuf-codec/decode/types')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$networkId = ''
  let field$chainId = ''
  let field$confirmations = 0
  let field$name = ''
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$networkId = string(data)
        break

      case 2:
        field$chainId = string(data)
        break

      case 3:
        field$confirmations = uint32(data)
        break

      case 4:
        field$name = string(data)
        break
    }
  }
  return {
    networkId: field$networkId,
    chainId: field$chainId,
    confirmations: field$confirmations,
    name: field$name
  }
}
