/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { string, uint32 } = require('protobuf-codec/encode/types')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.networkId) writer.bytes(1, obj.networkId, string)
  if (obj.chainId) writer.bytes(2, obj.chainId, string)
  if (obj.confirmations) writer.varint(3, obj.confirmations, uint32)
  if (obj.name) writer.bytes(4, obj.name, string)

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
