/// autogenerated by protoc-plugin-js
import type { ProposalParameters } from '../ProposalParameters'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): ProposalParameters
