/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { ProposalParameters } from '../ProposalParameters'
export function encode(
  obj?: PartialDeep<ProposalParameters>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
