/// autogenerated by protoc-plugin-js
import type { ProposalRationale } from '../ProposalRationale'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): ProposalRationale
