/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { uint64 } = require('protobuf-codec/decode/types')
const _vega_EpochTimestamps = require('./../EpochTimestamps/decode.js')
const _vega_Node = require('./../Node/decode.js')
const _vega_Delegation = require('./../Delegation/decode.js')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$seq = 0n
  let field$timestamps = {}
  const field$validators = []
  const field$delegations = []
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$seq = uint64(data)
        break

      case 2:
        field$timestamps = _vega_EpochTimestamps.decode(data)
        break

      case 3:
        field$validators.push(_vega_Node.decode(data))
        break

      case 4:
        field$delegations.push(_vega_Delegation.decode(data))
        break
    }
  }
  return {
    seq: field$seq,
    timestamps: field$timestamps,
    validators: field$validators,
    delegations: field$delegations
  }
}
