'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');
var NodeSignatureKind = require('../NodeSignatureKind.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$submitter = '';
  let field$kind = 0;
  let field$validatorNodeId = '';
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$submitter = types.string(data);
        break

      case 2:
        field$kind = NodeSignatureKind.decode(data);
        break

      case 3:
        field$validatorNodeId = types.string(data);
        break
    }
  }
  return {
    submitter: field$submitter,
    kind: field$kind,
    validatorNodeId: field$validatorNodeId
  }
}

exports.decode = decode;
