'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');
var NodeSignatureKind = require('../NodeSignatureKind.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.submitter) writer.bytes(1, obj.submitter, types.string);
  if (obj.kind) writer.varint(2, obj.kind, NodeSignatureKind);
  if (obj.validatorNodeId) writer.bytes(3, obj.validatorNodeId, types.string);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
