/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { string } = require('protobuf-codec/encode/types')
const _vega_KeyValueBundle = require('./../KeyValueBundle/encode.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.stateVarId) writer.bytes(1, obj.stateVarId, string)
  if (obj.eventId) writer.bytes(2, obj.eventId, string)
  if (obj.kvb?.length)
    obj.kvb.forEach((v) => writer.bytes(3, _vega_KeyValueBundle.encode(v)))

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
