/// autogenerated by protoc-plugin-js
import type { ERC20Update } from './ERC20Update'

export * from './AssetDetailsUpdate/encode.js'
export * from './AssetDetailsUpdate/decode.js'

export type AssetDetailsUpdate = {
  quantum: string
  source: { erc20: ERC20Update } | null
}
