/// autogenerated by protoc-plugin-js

export * from './CompositePriceSource/encode.js'
export * from './CompositePriceSource/decode.js'

export type CompositePriceSource = {
  priceSource: string
  price: string
  lastUpdated: bigint
}
