/// autogenerated by protoc-plugin-js
import type { LiteralUnion } from 'type-fest'

export const COMPOSITE_PRICE_TYPE_UNSPECIFIED = 0
export const COMPOSITE_PRICE_TYPE_WEIGHTED = 1
export const COMPOSITE_PRICE_TYPE_MEDIAN = 2
export const COMPOSITE_PRICE_TYPE_LAST_TRADE = 3

export type Values = 0 | 1 | 2 | 3
export type Names =
  | 'COMPOSITE_PRICE_TYPE_UNSPECIFIED'
  | 'COMPOSITE_PRICE_TYPE_WEIGHTED'
  | 'COMPOSITE_PRICE_TYPE_MEDIAN'
  | 'COMPOSITE_PRICE_TYPE_LAST_TRADE'

export const enum CompositePriceType {
  COMPOSITE_PRICE_TYPE_UNSPECIFIED = 0,
  COMPOSITE_PRICE_TYPE_WEIGHTED = 1,
  COMPOSITE_PRICE_TYPE_MEDIAN = 2,
  COMPOSITE_PRICE_TYPE_LAST_TRADE = 3
}

declare const enumValues: Map<Names, Values>
declare const enumNames: Map<Values, Names>

export function encode(
  value: Values | Names,
  buf: Uint8Array,
  byteOffset: number
): Uint8Array

export function decode(varint: bigint): LiteralUnion<Names, number>

export function encodingLength(value: LiteralUnion<Values, number>): number

export function stringify(int: Values): LiteralUnion<Names, undefined>

export function parse(str: Names): LiteralUnion<Values, undefined>
