/// autogenerated by protoc-plugin-js

export * from './DataSourceSpecToPerpetualBinding/encode.js'
export * from './DataSourceSpecToPerpetualBinding/decode.js'

export type DataSourceSpecToPerpetualBinding = {
  settlementDataProperty: string
  settlementScheduleProperty: string
}
