/// autogenerated by protoc-plugin-js

export * from './DiscountFactors/encode.js'
export * from './DiscountFactors/decode.js'

export type DiscountFactors = {
  infrastructureDiscountFactor: string
  liquidityDiscountFactor: string
  makerDiscountFactor: string
}
