/// autogenerated by protoc-plugin-js
import type { LiteralUnion } from 'type-fest'

export const DISPATCH_METRIC_UNSPECIFIED = 0
export const DISPATCH_METRIC_MAKER_FEES_PAID = 1
export const DISPATCH_METRIC_MAKER_FEES_RECEIVED = 2
export const DISPATCH_METRIC_LP_FEES_RECEIVED = 3
export const DISPATCH_METRIC_MARKET_VALUE = 4
export const DISPATCH_METRIC_AVERAGE_POSITION = 5
export const DISPATCH_METRIC_RELATIVE_RETURN = 6
export const DISPATCH_METRIC_RETURN_VOLATILITY = 7
export const DISPATCH_METRIC_VALIDATOR_RANKING = 8
export const DISPATCH_METRIC_REALISED_RETURN = 9

export type Values = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
export type Names =
  | 'DISPATCH_METRIC_UNSPECIFIED'
  | 'DISPATCH_METRIC_MAKER_FEES_PAID'
  | 'DISPATCH_METRIC_MAKER_FEES_RECEIVED'
  | 'DISPATCH_METRIC_LP_FEES_RECEIVED'
  | 'DISPATCH_METRIC_MARKET_VALUE'
  | 'DISPATCH_METRIC_AVERAGE_POSITION'
  | 'DISPATCH_METRIC_RELATIVE_RETURN'
  | 'DISPATCH_METRIC_RETURN_VOLATILITY'
  | 'DISPATCH_METRIC_VALIDATOR_RANKING'
  | 'DISPATCH_METRIC_REALISED_RETURN'

export const enum DispatchMetric {
  DISPATCH_METRIC_UNSPECIFIED = 0,
  DISPATCH_METRIC_MAKER_FEES_PAID = 1,
  DISPATCH_METRIC_MAKER_FEES_RECEIVED = 2,
  DISPATCH_METRIC_LP_FEES_RECEIVED = 3,
  DISPATCH_METRIC_MARKET_VALUE = 4,
  DISPATCH_METRIC_AVERAGE_POSITION = 5,
  DISPATCH_METRIC_RELATIVE_RETURN = 6,
  DISPATCH_METRIC_RETURN_VOLATILITY = 7,
  DISPATCH_METRIC_VALIDATOR_RANKING = 8,
  DISPATCH_METRIC_REALISED_RETURN = 9
}

declare const enumValues: Map<Names, Values>
declare const enumNames: Map<Values, Names>

export function encode(
  value: Values | Names,
  buf: Uint8Array,
  byteOffset: number
): Uint8Array

export function decode(varint: bigint): LiteralUnion<Names, number>

export function encodingLength(value: LiteralUnion<Values, number>): number

export function stringify(int: Values): LiteralUnion<Names, undefined>

export function parse(str: Names): LiteralUnion<Values, undefined>
