/// autogenerated by protoc-plugin-js

export * from './EpochRewardSummary/encode.js'
export * from './EpochRewardSummary/decode.js'

export type EpochRewardSummary = {
  epoch: bigint
  assetId: string
  marketId: string
  rewardType: string
  amount: string
}
