/// autogenerated by protoc-plugin-js

export * from './ERC20ThresholdSet/encode.js'
export * from './ERC20ThresholdSet/decode.js'

export type ERC20ThresholdSet = {
  newThreshold: number
  nonce: string
  blockTime: bigint
}
