/// autogenerated by protoc-plugin-js

export * from './ERC20SignerAdded/encode.js'
export * from './ERC20SignerAdded/decode.js'

export type ERC20SignerAdded = {
  newSigner: string
  nonce: string
  blockTime: bigint
}
