/// autogenerated by protoc-plugin-js
import type { ListValue } from './../google/protobuf/ListValue'
import type { Value } from './../google/protobuf/Value'
import type { EthCallTrigger } from './EthCallTrigger'

export * from './EthCallSpec/encode.js'
export * from './EthCallSpec/decode.js'

export type EthCallSpec = {
  address: string
  abi: ListValue
  method: string
  args: Value[]
  trigger: EthCallTrigger
}
