/// autogenerated by protoc-plugin-js

export * from './EthereumContractConfig/encode.js'
export * from './EthereumContractConfig/decode.js'

export type EthereumContractConfig = {
  address: string
  deploymentBlockHeight: bigint
}
