/// autogenerated by protoc-plugin-js
import type { EthereumL2Config } from './EthereumL2Config'

export * from './EthereumL2Configs/encode.js'
export * from './EthereumL2Configs/decode.js'

export type EthereumL2Configs = {
  configs: EthereumL2Config[]
}
