/// autogenerated by protoc-plugin-js

export * from './EthereumL2Config/encode.js'
export * from './EthereumL2Config/decode.js'

export type EthereumL2Config = {
  networkId: string
  chainId: string
  confirmations: number
  name: string
}
