/// autogenerated by protoc-plugin-js
import type { EVMBridgeConfig } from './EVMBridgeConfig'

export * from './EVMBridgeConfigs/encode.js'
export * from './EVMBridgeConfigs/decode.js'

export type EVMBridgeConfigs = {
  configs: EVMBridgeConfig[]
}
