/// autogenerated by protoc-plugin-js
import type { EthereumContractConfig } from './EthereumContractConfig'

export * from './EVMBridgeConfig/encode.js'
export * from './EVMBridgeConfig/decode.js'

export type EVMBridgeConfig = {
  networkId: string
  chainId: string
  collateralBridgeContract: EthereumContractConfig
  confirmations: number
  multisigControlContract: EthereumContractConfig
  blockTime: string
  name: string
}
