/// autogenerated by protoc-plugin-js

export * from './Fee/encode.js'
export * from './Fee/decode.js'

export type Fee = {
  makerFee: string
  infrastructureFee: string
  liquidityFee: string
  makerFeeVolumeDiscount: string
  infrastructureFeeVolumeDiscount: string
  liquidityFeeVolumeDiscount: string
  makerFeeReferrerDiscount: string
  infrastructureFeeReferrerDiscount: string
  liquidityFeeReferrerDiscount: string
  treasuryFee: string
  buyBackFee: string
  highVolumeMakerFee: string
}
