/// autogenerated by protoc-plugin-js
import type { FeeFactors } from './FeeFactors'
import type { LiquidityFeeSettings } from './LiquidityFeeSettings'

export * from './Fees/encode.js'
export * from './Fees/decode.js'

export type Fees = {
  factors: FeeFactors
  liquidityFeeSettings: LiquidityFeeSettings
}
