/// autogenerated by protoc-plugin-js
import type { DataSourceSpec } from './DataSourceSpec'
import type { DataSourceSpecToFutureBinding } from './DataSourceSpecToFutureBinding'

export * from './Future/encode.js'
export * from './Future/decode.js'

export type Future = {
  settlementAsset: string
  quoteName: string
  dataSourceSpecForSettlementData: DataSourceSpec
  dataSourceSpecForTradingTermination: DataSourceSpec
  dataSourceSpecBinding: DataSourceSpecToFutureBinding
}
