/// autogenerated by protoc-plugin-js
import type { AccountDetails } from './AccountDetails'
import type { TransferType } from './TransferType'

export * from './LedgerEntry/encode.js'
export * from './LedgerEntry/decode.js'

export type LedgerEntry = {
  fromAccount: AccountDetails
  toAccount: AccountDetails
  amount: string
  type: TransferType
  timestamp: bigint
  fromAccountBalance: string
  toAccountBalance: string
  transferId: string | null
}
