/// autogenerated by protoc-plugin-js
import type { LiquidityOrderReference } from './LiquidityOrderReference'
import type { Status } from './LiquidityProvisionV2/Status'

export * from './LiquidityProvisionV2/encode.js'
export * from './LiquidityProvisionV2/decode.js'
export * as Status from './LiquidityProvisionV2/Status.js'

export type LiquidityProvisionV2 = {
  id: string
  partyId: string
  createdAt: bigint
  updatedAt: bigint
  marketId: string
  commitmentAmount: string
  fee: string
  sells: LiquidityOrderReference[]
  buys: LiquidityOrderReference[]
  version: bigint
  status: Status
  reference: string
}
