/// autogenerated by protoc-plugin-js

module.exports = {
  ...require('./LiquidityProvisionV2/encode.js'),
  ...require('./LiquidityProvisionV2/decode.js'),
  Status: require('./LiquidityProvisionV2/Status.js')
}
