/// autogenerated by protoc-plugin-js

export * from './LiquidityProviderFeeShare/encode.js'
export * from './LiquidityProviderFeeShare/decode.js'

export type LiquidityProviderFeeShare = {
  party: string
  equityLikeShare: string
  averageEntryValuation: string
  averageScore: string
  virtualStake: string
}
