/// autogenerated by protoc-plugin-js
import type { Method } from './LiquidityFeeSettings/Method'

export * from './LiquidityFeeSettings/encode.js'
export * from './LiquidityFeeSettings/decode.js'
export * as Method from './LiquidityFeeSettings/Method.js'

export type LiquidityFeeSettings = {
  method: Method
  feeConstant: string | null
}
