/// autogenerated by protoc-plugin-js

export * from './LiquiditySLAParameters/encode.js'
export * from './LiquiditySLAParameters/decode.js'

export type LiquiditySLAParameters = {
  priceRange: string
  commitmentMinTimeFraction: string
  providersFeeCalculationTimeStep: bigint
  performanceHysteresisEpochs: bigint
  slaCompetitionFactor: string
}
