/// autogenerated by protoc-plugin-js
import type { LogNormalModelParams } from './LogNormalModelParams'
import type { RiskFactorOverride } from './RiskFactorOverride'

export * from './LogNormalRiskModel/encode.js'
export * from './LogNormalRiskModel/decode.js'

export type LogNormalRiskModel = {
  riskAversionParameter: number
  tau: number
  params: LogNormalModelParams
  riskFactorOverride: RiskFactorOverride | null
}
