/// autogenerated by protoc-plugin-js
import type { LongBlockAuction } from './LongBlockAuction'

export * from './LongBlockAuctionDurationTable/encode.js'
export * from './LongBlockAuctionDurationTable/decode.js'

export type LongBlockAuctionDurationTable = {
  thresholdAndDuration: LongBlockAuction[]
}
