/// autogenerated by protoc-plugin-js

export * from './MarketTimestamps/encode.js'
export * from './MarketTimestamps/decode.js'

export type MarketTimestamps = {
  proposed: bigint
  pending: bigint
  open: bigint
  close: bigint
}
