/// autogenerated by protoc-plugin-js
import type { AccountType } from './AccountType'
import type { DataSourceDefinition } from './DataSourceDefinition'
import type { SpecBindingForCompositePrice } from './SpecBindingForCompositePrice'
import type { DataSourceSpecToAutomatedPurchaseBinding } from './DataSourceSpecToAutomatedPurchaseBinding'

export * from './NewProtocolAutomatedPurchaseChanges/encode.js'
export * from './NewProtocolAutomatedPurchaseChanges/decode.js'

export type NewProtocolAutomatedPurchaseChanges = {
  from: string
  fromAccountType: AccountType
  toAccountType: AccountType
  marketId: string
  priceOracle: DataSourceDefinition
  priceOracleSpecBinding: SpecBindingForCompositePrice
  oracleOffsetFactor: string
  auctionSchedule: DataSourceDefinition
  auctionVolumeSnapshotSchedule: DataSourceDefinition
  automatedPurchaseSpecBinding: DataSourceSpecToAutomatedPurchaseBinding
  auctionDuration: string
  minimumAuctionSize: string
  maximumAuctionSize: string
  expiryTimestamp: bigint
  oraclePriceStalenessTolerance: string
}
