/// autogenerated by protoc-plugin-js
import type { InstrumentConfiguration } from './InstrumentConfiguration'
import type { PriceMonitoringParameters } from './PriceMonitoringParameters'
import type { TargetStakeParameters } from './TargetStakeParameters'
import type { SimpleModelParams } from './SimpleModelParams'
import type { LogNormalRiskModel } from './LogNormalRiskModel'
import type { LiquiditySLAParameters } from './LiquiditySLAParameters'

export * from './NewSpotMarketConfiguration/encode.js'
export * from './NewSpotMarketConfiguration/decode.js'

export type NewSpotMarketConfiguration = {
  instrument: InstrumentConfiguration
  decimalPlaces: bigint
  metadata: string[]
  priceMonitoringParameters: PriceMonitoringParameters
  targetStakeParameters: TargetStakeParameters
  risk_parameters:
    | { simple: SimpleModelParams }
    | { logNormal: LogNormalRiskModel }
    | null
  positionDecimalPlaces: bigint
  slaParams: LiquiditySLAParameters
}
