/// autogenerated by protoc-plugin-js
import type { NewSpotMarketConfiguration } from './NewSpotMarketConfiguration'

export * from './NewSpotMarket/encode.js'
export * from './NewSpotMarket/decode.js'

export type NewSpotMarket = {
  changes: NewSpotMarketConfiguration
}
