/// autogenerated by protoc-plugin-js

export * from './NodeSet/encode.js'
export * from './NodeSet/decode.js'

export type NodeSet = {
  total: number
  inactive: number
  promoted: string[]
  demoted: string[]
  maximum: number | null
}
