/// autogenerated by protoc-plugin-js
import type { Metadata } from './Metadata'

export * from './Party/encode.js'
export * from './Party/decode.js'

export type Party = {
  id: string
  alias: string
  metadata: Metadata[]
}
