/// autogenerated by protoc-plugin-js
import type { PositionStatus } from './PositionStatus'

export * from './Position/encode.js'
export * from './Position/decode.js'

export type Position = {
  marketId: string
  partyId: string
  openVolume: bigint
  realisedPnl: string
  unrealisedPnl: string
  averageEntryPrice: string
  updatedAt: bigint
  lossSocialisationAmount: string
  positionStatus: PositionStatus
  takerFeesPaid: string
  makerFeesReceived: string
  feesPaid: string
  takerFeesPaidSince: string
  makerFeesReceivedSince: string
  feesPaidSince: string
  fundingPaymentAmount: string
  fundingPaymentAmountSince: string
}
