/// autogenerated by protoc-plugin-js

export * from './PriceMonitoringTrigger/encode.js'
export * from './PriceMonitoringTrigger/decode.js'

export type PriceMonitoringTrigger = {
  horizon: bigint
  probability: string
  auctionExtension: bigint
}
