/// autogenerated by protoc-plugin-js

export * from './ProposalParameters/encode.js'
export * from './ProposalParameters/decode.js'

export type ProposalParameters = {
  minClose: bigint
  maxClose: bigint
  minEnact: bigint
  maxEnact: bigint
  requiredParticipation: string
  requiredMajority: string
  minProposerBalance: string
  minVoterBalance: string
  requiredParticipationLp: string
  requiredMajorityLp: string
  minEquityLikeShare: string
}
