/// autogenerated by protoc-plugin-js
import type { BenefitTier } from './BenefitTier'
import type { StakingTier } from './StakingTier'

export * from './ReferralProgram/encode.js'
export * from './ReferralProgram/decode.js'

export type ReferralProgram = {
  version: bigint
  id: string
  benefitTiers: BenefitTier[]
  endOfProgramTimestamp: bigint
  windowLength: bigint
  stakingTiers: StakingTier[]
}
