/// autogenerated by protoc-plugin-js

export * from './ScalingFactors/encode.js'
export * from './ScalingFactors/decode.js'

export type ScalingFactors = {
  searchLevel: number
  initialMargin: number
  collateralRelease: number
}
