/// autogenerated by protoc-plugin-js

export * from './SimpleModelParams/encode.js'
export * from './SimpleModelParams/decode.js'

export type SimpleModelParams = {
  factorLong: number
  factorShort: number
  maxMoveUp: number
  minMoveDown: number
  probabilityOfTrading: number
}
