/// autogenerated by protoc-plugin-js

export * from './SpecBindingForCompositePrice/encode.js'
export * from './SpecBindingForCompositePrice/decode.js'

export type SpecBindingForCompositePrice = {
  priceSourceProperty: string
}
