/// autogenerated by protoc-plugin-js
import type { StakeDeposited } from './StakeDeposited'
import type { StakeRemoved } from './StakeRemoved'
import type { StakeTotalSupply } from './StakeTotalSupply'

export * from './StakingEvent/encode.js'
export * from './StakingEvent/decode.js'

export type StakingEvent = {
  index: bigint
  block: bigint
  action:
    | { stakeDeposited: StakeDeposited }
    | { stakeRemoved: StakeRemoved }
    | { totalSupply: StakeTotalSupply }
    | null
}
