/// autogenerated by protoc-plugin-js
import type { ExpiryStrategy } from './StopOrder/ExpiryStrategy'
import type { TriggerDirection } from './StopOrder/TriggerDirection'
import type { Status } from './StopOrder/Status'
import type { RejectionReason } from './StopOrder/RejectionReason'
import type { SizeOverrideSetting } from './StopOrder/SizeOverrideSetting'
import type { SizeOverrideValue } from './StopOrder/SizeOverrideValue'

export * from './StopOrder/encode.js'
export * from './StopOrder/decode.js'
export * as SizeOverrideSetting from './StopOrder/SizeOverrideSetting.js'
export * as ExpiryStrategy from './StopOrder/ExpiryStrategy.js'
export * as TriggerDirection from './StopOrder/TriggerDirection.js'
export * as Status from './StopOrder/Status.js'
export * as RejectionReason from './StopOrder/RejectionReason.js'

export * as SizeOverrideValue from './StopOrder/SizeOverrideValue.js'

export type StopOrder = {
  id: string
  ocoLinkId: string | null
  expiresAt: bigint | null
  expiryStrategy: ExpiryStrategy | null
  triggerDirection: TriggerDirection
  status: Status
  createdAt: bigint
  updatedAt: bigint | null
  orderId: string
  partyId: string
  marketId: string
  rejectionReason: RejectionReason | null
  sizeOverrideSetting: SizeOverrideSetting
  sizeOverrideValue: SizeOverrideValue | null
  trigger: { price: string } | { trailingPercentOffset: string } | null
}
