/// autogenerated by protoc-plugin-js
import type { Instrument } from './Instrument'
import type { MarginCalculator } from './MarginCalculator'
import type { LogNormalRiskModel } from './LogNormalRiskModel'
import type { SimpleRiskModel } from './SimpleRiskModel'

export * from './TradableInstrument/encode.js'
export * from './TradableInstrument/decode.js'

export type TradableInstrument = {
  instrument: Instrument
  marginCalculator: MarginCalculator
  riskModel:
    | { logNormalRiskModel: LogNormalRiskModel }
    | { simpleRiskModel: SimpleRiskModel }
    | null
}
