/// autogenerated by protoc-plugin-js
import type { UpdateFutureProduct } from './UpdateFutureProduct'

export * from './UpdateInstrumentConfiguration/encode.js'
export * from './UpdateInstrumentConfiguration/decode.js'

export type UpdateInstrumentConfiguration = {
  code: string
  product: { future: UpdateFutureProduct } | null
}
