/// autogenerated by protoc-plugin-js
import type { DataSourceDefinition } from './DataSourceDefinition'
import type { DataSourceSpecToFutureBinding } from './DataSourceSpecToFutureBinding'

export * from './UpdateFutureProduct/encode.js'
export * from './UpdateFutureProduct/decode.js'

export type UpdateFutureProduct = {
  quoteName: string
  dataSourceSpecForSettlementData: DataSourceDefinition
  dataSourceSpecForTradingTermination: DataSourceDefinition
  dataSourceSpecBinding: DataSourceSpecToFutureBinding
}
