/// autogenerated by protoc-plugin-js
import type { UpdateMarketStateConfiguration } from './UpdateMarketStateConfiguration'

export * from './UpdateMarketState/encode.js'
export * from './UpdateMarketState/decode.js'

export type UpdateMarketState = {
  changes: UpdateMarketStateConfiguration
}
