/// autogenerated by protoc-plugin-js
import type { PriceMonitoringParameters } from './PriceMonitoringParameters'
import type { TargetStakeParameters } from './TargetStakeParameters'
import type { SimpleModelParams } from './SimpleModelParams'
import type { LogNormalRiskModel } from './LogNormalRiskModel'
import type { LiquiditySLAParameters } from './LiquiditySLAParameters'

export * from './UpdateSpotMarketConfiguration/encode.js'
export * from './UpdateSpotMarketConfiguration/decode.js'

export type UpdateSpotMarketConfiguration = {
  metadata: string[]
  priceMonitoringParameters: PriceMonitoringParameters
  targetStakeParameters: TargetStakeParameters
  riskParameters:
    | { simple: SimpleModelParams }
    | { logNormal: LogNormalRiskModel }
    | null
  slaParams: LiquiditySLAParameters
}
