/// autogenerated by protoc-plugin-js
import type { VolumeDiscountProgramChanges } from './VolumeDiscountProgramChanges'

export * from './UpdateVolumeDiscountProgram/encode.js'
export * from './UpdateVolumeDiscountProgram/decode.js'

export type UpdateVolumeDiscountProgram = {
  changes: VolumeDiscountProgramChanges
}
