/// autogenerated by protoc-plugin-js
import type { UpdateInstrumentConfiguration } from './UpdateInstrumentConfiguration'
import type { PriceMonitoringParameters } from './PriceMonitoringParameters'
import type { LiquidityMonitoringParameters } from './LiquidityMonitoringParameters'
import type { SimpleModelParams } from './SimpleModelParams'
import type { LogNormalRiskModel } from './LogNormalRiskModel'
import type { LiquiditySLAParameters } from './LiquiditySLAParameters'
import type { LiquidityFeeSettings } from './LiquidityFeeSettings'
import type { LiquidationStrategy } from './LiquidationStrategy'
import type { CompositePriceConfiguration } from './CompositePriceConfiguration'

export * from './UpdateMarketConfiguration/encode.js'
export * from './UpdateMarketConfiguration/decode.js'

export type UpdateMarketConfiguration = {
  instrument: UpdateInstrumentConfiguration
  metadata: string[]
  priceMonitoringParameters: PriceMonitoringParameters
  liquidityMonitoringParameters: LiquidityMonitoringParameters
  riskParameters:
    | { simple: SimpleModelParams }
    | { logNormal: LogNormalRiskModel }
    | null
  lpPriceRange: string | null
  linearSlippageFactor: string
  quadraticSlippageFactor: string
  liquiditySlaParameters: LiquiditySLAParameters
  liquidityFeeSettings: LiquidityFeeSettings
  liquidationStrategy: LiquidationStrategy
  markPriceConfiguration: CompositePriceConfiguration
  tickSize: string
}
