/// autogenerated by protoc-plugin-js
import type { ReferralProgram } from './ReferralProgram'

export * from './UpdateReferralProgram/encode.js'
export * from './UpdateReferralProgram/decode.js'

export type UpdateReferralProgram = {
  changes: ReferralProgram
}
