/// autogenerated by protoc-plugin-js
import type { MarketStateUpdateType } from './MarketStateUpdateType'

export * from './UpdateMarketStateConfiguration/encode.js'
export * from './UpdateMarketStateConfiguration/decode.js'

export type UpdateMarketStateConfiguration = {
  marketId: string
  updateType: MarketStateUpdateType
  price: string | null
}
