/// autogenerated by protoc-plugin-js
import type { UpdateSpotMarketConfiguration } from './UpdateSpotMarketConfiguration'

export * from './UpdateSpotMarket/encode.js'
export * from './UpdateSpotMarket/decode.js'

export type UpdateSpotMarket = {
  marketId: string
  changes: UpdateSpotMarketConfiguration
}
