/// autogenerated by protoc-plugin-js
import type { VolumeRebateBenefitTier } from './VolumeRebateBenefitTier'

export * from './VolumeRebateProgramChanges/encode.js'
export * from './VolumeRebateProgramChanges/decode.js'

export type VolumeRebateProgramChanges = {
  benefitTiers: VolumeRebateBenefitTier[]
  endOfProgramTimestamp: bigint
  windowLength: bigint
}
