/// autogenerated by protoc-plugin-js
import type { VolumeBenefitTier } from './VolumeBenefitTier'

export * from './VolumeDiscountProgramChanges/encode.js'
export * from './VolumeDiscountProgramChanges/decode.js'

export type VolumeDiscountProgramChanges = {
  benefitTiers: VolumeBenefitTier[]
  endOfProgramTimestamp: bigint
  windowLength: bigint
}
