/// autogenerated by protoc-plugin-js

module.exports = {
  ...require('./Vote/encode.js'),
  ...require('./Vote/decode.js'),
  Value: require('./Vote/Value.js'),
  PerMarketEquityLikeShareWeightEntry: require('./Vote/PerMarketEquityLikeShareWeightEntry.js')
}
