'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');
var encode$1 = require('../FutureProduct/encode.cjs');
var encode$2 = require('../SpotProduct/encode.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.name) writer.bytes(1, obj.name, types.string);
  if (obj.code) writer.bytes(2, obj.code, types.string);

  if (obj.product?.future ?? obj.future)
    writer.bytes(
      100,
      encode$1.encode(obj.product?.future ?? obj.future)
    );
  if (obj.product?.spot ?? obj.spot)
    writer.bytes(101, encode$2.encode(obj.product?.spot ?? obj.spot));

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
