'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');
var decode$1 = require('../Epoch/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$epoch = {};
  let field$offline = 0n;
  let field$online = 0n;
  let field$totalRewards = 0;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$epoch = decode$1.decode(data);
        break

      case 2:
        field$offline = types.uint64(data);
        break

      case 3:
        field$online = types.uint64(data);
        break

      case 4:
        field$totalRewards = types.double(data);
        break
    }
  }
  return {
    epoch: field$epoch,
    offline: field$offline,
    online: field$online,
    totalRewards: field$totalRewards
  }
}

exports.decode = decode;
