/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { DataSourceSpecConfigurationTime } from '../DataSourceSpecConfigurationTime'
export function encode(
  obj?: PartialDeep<DataSourceSpecConfigurationTime>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
