'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.mu) writer.fixed64(1, obj.mu, types.double);
  if (obj.r) writer.fixed64(2, obj.r, types.double);
  if (obj.sigma) writer.fixed64(3, obj.sigma, types.double);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
