/// autogenerated by protoc-plugin-js
import type { LiquidityFeeSettings } from '../LiquidityFeeSettings'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): LiquidityFeeSettings
