/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { LiquidityFeeSettings } from '../LiquidityFeeSettings'
export function encode(
  obj?: PartialDeep<LiquidityFeeSettings>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
