/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { uint32, string, int64 } = require('protobuf-codec/encode/types')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.newThreshold) writer.varint(1, obj.newThreshold, uint32)
  if (obj.nonce) writer.bytes(2, obj.nonce, string)
  if (obj.blockTime) writer.varint(3, obj.blockTime, int64)

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
