/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { DelayedTransactionsWrapper } from '../DelayedTransactionsWrapper'
export function encode(
  obj?: PartialDeep<DelayedTransactionsWrapper>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
