/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { string } = require('protobuf-codec/decode/types')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$minimumRunningNotionalTakerVolume = ''
  let field$minimumEpochs = ''
  let field$referralRewardFactor = ''
  let field$referralDiscountFactor = ''
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$minimumRunningNotionalTakerVolume = string(data)
        break

      case 2:
        field$minimumEpochs = string(data)
        break

      case 3:
        field$referralRewardFactor = string(data)
        break

      case 4:
        field$referralDiscountFactor = string(data)
        break
    }
  }
  return {
    minimumRunningNotionalTakerVolume: field$minimumRunningNotionalTakerVolume,
    minimumEpochs: field$minimumEpochs,
    referralRewardFactor: field$referralRewardFactor,
    referralDiscountFactor: field$referralDiscountFactor
  }
}
