/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { string, uint64 } = require('protobuf-codec/decode/types')
const _vega_RewardFactors = require('./../RewardFactors/decode.js')
const _vega_DiscountFactors = require('./../DiscountFactors/decode.js')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$minimumRunningNotionalTakerVolume = ''
  let field$minimumEpochs = ''
  let field$referralRewardFactor = ''
  let field$referralDiscountFactor = ''
  let field$referralRewardFactors = {}
  let field$referralDiscountFactors = {}
  let field$tierNumber = null
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$minimumRunningNotionalTakerVolume = string(data)
        break

      case 2:
        field$minimumEpochs = string(data)
        break

      case 3:
        field$referralRewardFactor = string(data)
        break

      case 4:
        field$referralDiscountFactor = string(data)
        break

      case 5:
        field$referralRewardFactors = _vega_RewardFactors.decode(data)
        break

      case 6:
        field$referralDiscountFactors = _vega_DiscountFactors.decode(data)
        break

      case 7:
        field$tierNumber = uint64(data)
        break
    }
  }
  return {
    minimumRunningNotionalTakerVolume: field$minimumRunningNotionalTakerVolume,
    minimumEpochs: field$minimumEpochs,
    referralRewardFactor: field$referralRewardFactor,
    referralDiscountFactor: field$referralDiscountFactor,
    referralRewardFactors: field$referralRewardFactors,
    referralDiscountFactors: field$referralDiscountFactors,
    tierNumber: field$tierNumber
  }
}
