/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { string, uint64 } = require('protobuf-codec/encode/types')
const _vega_RewardFactors = require('./../RewardFactors/encode.js')
const _vega_DiscountFactors = require('./../DiscountFactors/encode.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.minimumRunningNotionalTakerVolume)
    writer.bytes(1, obj.minimumRunningNotionalTakerVolume, string)
  if (obj.minimumEpochs) writer.bytes(2, obj.minimumEpochs, string)
  if (obj.referralRewardFactor)
    writer.bytes(3, obj.referralRewardFactor, string)
  if (obj.referralDiscountFactor)
    writer.bytes(4, obj.referralDiscountFactor, string)
  if (obj.referralRewardFactors)
    writer.bytes(5, _vega_RewardFactors.encode(obj.referralRewardFactors))
  if (obj.referralDiscountFactors)
    writer.bytes(6, _vega_DiscountFactors.encode(obj.referralDiscountFactors))
  if (obj.tierNumber) writer.varint(7, obj.tierNumber, uint64)

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
