'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');
var Status = require('./Status.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.id) writer.bytes(1, obj.id, types.string);
  if (obj.status) writer.varint(2, obj.status, Status);
  if (obj.partyId) writer.bytes(3, obj.partyId, types.string);
  if (obj.asset) writer.bytes(4, obj.asset, types.string);
  if (obj.amount) writer.bytes(5, obj.amount, types.string);
  if (obj.txHash) writer.bytes(6, obj.txHash, types.string);
  if (obj.creditedTimestamp) writer.varint(7, obj.creditedTimestamp, types.int64);
  if (obj.createdTimestamp) writer.varint(8, obj.createdTimestamp, types.int64);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
