/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { DataSourceSpecToAutomatedPurchaseBinding } from '../DataSourceSpecToAutomatedPurchaseBinding'
export function encode(
  obj?: PartialDeep<DataSourceSpecToAutomatedPurchaseBinding>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
