/// autogenerated by protoc-plugin-js
import type { BatchProposalSubmission } from '../BatchProposalSubmission'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): BatchProposalSubmission
