/// autogenerated by protoc-plugin-js
import type { EthereumContractConfig } from '../EthereumContractConfig'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): EthereumContractConfig
