'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');
var decode$1 = require('../OrderSubmission/decode.cjs');
var ExpiryStrategy = require('../../../StopOrder/ExpiryStrategy.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$orderSubmission = {};
  let field$expiresAt = null;
  let field$expiryStrategy = null;
  let field$trigger = null;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$orderSubmission = decode$1.decode(data);
        break

      case 2:
        field$expiresAt = types.int64(data);
        break

      case 3:
        field$expiryStrategy = ExpiryStrategy.decode(data);
        break

      case 100:
        field$trigger = { price: types.string(data) };
        break

      case 101:
        field$trigger = { trailingPercentOffset: types.string(data) };
        break
    }
  }
  return {
    orderSubmission: field$orderSubmission,
    expiresAt: field$expiresAt,
    expiryStrategy: field$expiryStrategy,
    trigger: field$trigger
  }
}

exports.decode = decode;
