'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');
var encode$1 = require('../OrderSubmission/encode.cjs');
var ExpiryStrategy = require('../../../StopOrder/ExpiryStrategy.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.orderSubmission)
    writer.bytes(
      1,
      encode$1.encode(obj.orderSubmission)
    );
  if (obj.expiresAt) writer.varint(2, obj.expiresAt, types.int64);
  if (obj.expiryStrategy)
    writer.varint(3, obj.expiryStrategy, ExpiryStrategy);

  if (obj.trigger?.price ?? obj.price)
    writer.bytes(100, obj.trigger?.price ?? obj.price, types.string);
  if (obj.trigger?.trailingPercentOffset ?? obj.trailingPercentOffset)
    writer.bytes(
      101,
      obj.trigger?.trailingPercentOffset ?? obj.trailingPercentOffset,
      types.string
    );

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
