/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { ChainEvent } from '../ChainEvent'
export function encode(
  obj?: PartialDeep<ChainEvent>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
