'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$value = '';
  let field$algo = '';
  let field$version = 0;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$value = types.string(data);
        break

      case 2:
        field$algo = types.string(data);
        break

      case 3:
        field$version = types.uint32(data);
        break
    }
  }
  return { value: field$value, algo: field$algo, version: field$version }
}

exports.decode = decode;
