/// autogenerated by protoc-plugin-js
import type { EthCallTrigger } from '../EthCallTrigger'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): EthCallTrigger
