/// autogenerated by protoc-plugin-js
import type { NetworkParameter } from '../NetworkParameter'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): NetworkParameter
