'use strict';

var assert = require('nanoassert');
var types = require('protobuf-codec/encode/types');
var types$1 = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

const STATE_UNSPECIFIED = 0;
const STATE_PROPOSED = 1;
const STATE_REJECTED = 2;
const STATE_PENDING = 3;
const STATE_CANCELLED = 4;
const STATE_ACTIVE = 5;
const STATE_SUSPENDED = 6;
const STATE_CLOSED = 7;
const STATE_TRADING_TERMINATED = 8;
const STATE_SETTLED = 9;

const enumValues = new Map([
  [0, 'STATE_UNSPECIFIED'],
  [1, 'STATE_PROPOSED'],
  [2, 'STATE_REJECTED'],
  [3, 'STATE_PENDING'],
  [4, 'STATE_CANCELLED'],
  [5, 'STATE_ACTIVE'],
  [6, 'STATE_SUSPENDED'],
  [7, 'STATE_CLOSED'],
  [8, 'STATE_TRADING_TERMINATED'],
  [9, 'STATE_SETTLED']
]);
const enumNames = new Map([
  ['STATE_UNSPECIFIED', 0],
  ['STATE_PROPOSED', 1],
  ['STATE_REJECTED', 2],
  ['STATE_PENDING', 3],
  ['STATE_CANCELLED', 4],
  ['STATE_ACTIVE', 5],
  ['STATE_SUSPENDED', 6],
  ['STATE_CLOSED', 7],
  ['STATE_TRADING_TERMINATED', 8],
  ['STATE_SETTLED', 9]
]);

function encode(value, buf, byteOffset = 0) {
  if (typeof value === 'string') return encode(parse(value), buf, byteOffset)
  if (value == null) throw new Error('Invalid State value (' + value + ')')

  return types.enumerable.encode(value, buf, byteOffset)
}

function decode(varint) {
  const int = types$1.enumerable(varint);

  return stringify(int) ?? int
}

function encodingLength(value) {
  if (typeof value === 'string') return encodingLength(parse(value))
  assert(value != null, 'Invalid State value (' + value + ')');

  if (0 <= value && value <= 9) return 1

  // enumerable max value in case of unknown value
  return 5
}

/**
 * Convert an enum value to it's human readable name.
 * Returns undefined on an unknown value.
 */
function stringify(int) {
  return enumValues.get(int)
}

/**
 * Convert an enum string names to it's machine integer value.
 * Returns undefined on an unknown name.
 */
function parse(str) {
  return enumNames.get(str)
}

exports.STATE_ACTIVE = STATE_ACTIVE;
exports.STATE_CANCELLED = STATE_CANCELLED;
exports.STATE_CLOSED = STATE_CLOSED;
exports.STATE_PENDING = STATE_PENDING;
exports.STATE_PROPOSED = STATE_PROPOSED;
exports.STATE_REJECTED = STATE_REJECTED;
exports.STATE_SETTLED = STATE_SETTLED;
exports.STATE_SUSPENDED = STATE_SUSPENDED;
exports.STATE_TRADING_TERMINATED = STATE_TRADING_TERMINATED;
exports.STATE_UNSPECIFIED = STATE_UNSPECIFIED;
exports.decode = decode;
exports.encode = encode;
exports.encodingLength = encodingLength;
exports.parse = parse;
exports.stringify = stringify;
