'use strict';

var assert = require('nanoassert');
var types = require('protobuf-codec/encode/types');
var types$1 = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

const TRADING_MODE_UNSPECIFIED = 0;
const TRADING_MODE_CONTINUOUS = 1;
const TRADING_MODE_BATCH_AUCTION = 2;
const TRADING_MODE_OPENING_AUCTION = 3;
const TRADING_MODE_MONITORING_AUCTION = 4;
const TRADING_MODE_NO_TRADING = 5;

const enumValues = new Map([
  [0, 'TRADING_MODE_UNSPECIFIED'],
  [1, 'TRADING_MODE_CONTINUOUS'],
  [2, 'TRADING_MODE_BATCH_AUCTION'],
  [3, 'TRADING_MODE_OPENING_AUCTION'],
  [4, 'TRADING_MODE_MONITORING_AUCTION'],
  [5, 'TRADING_MODE_NO_TRADING']
]);
const enumNames = new Map([
  ['TRADING_MODE_UNSPECIFIED', 0],
  ['TRADING_MODE_CONTINUOUS', 1],
  ['TRADING_MODE_BATCH_AUCTION', 2],
  ['TRADING_MODE_OPENING_AUCTION', 3],
  ['TRADING_MODE_MONITORING_AUCTION', 4],
  ['TRADING_MODE_NO_TRADING', 5]
]);

function encode(value, buf, byteOffset = 0) {
  if (typeof value === 'string') return encode(parse(value), buf, byteOffset)
  if (value == null)
    throw new Error('Invalid TradingMode value (' + value + ')')

  return types.enumerable.encode(value, buf, byteOffset)
}

function decode(varint) {
  const int = types$1.enumerable(varint);

  return stringify(int) ?? int
}

function encodingLength(value) {
  if (typeof value === 'string') return encodingLength(parse(value))
  assert(value != null, 'Invalid TradingMode value (' + value + ')');

  if (0 <= value && value <= 5) return 1

  // enumerable max value in case of unknown value
  return 5
}

/**
 * Convert an enum value to it's human readable name.
 * Returns undefined on an unknown value.
 */
function stringify(int) {
  return enumValues.get(int)
}

/**
 * Convert an enum string names to it's machine integer value.
 * Returns undefined on an unknown name.
 */
function parse(str) {
  return enumNames.get(str)
}

exports.TRADING_MODE_BATCH_AUCTION = TRADING_MODE_BATCH_AUCTION;
exports.TRADING_MODE_CONTINUOUS = TRADING_MODE_CONTINUOUS;
exports.TRADING_MODE_MONITORING_AUCTION = TRADING_MODE_MONITORING_AUCTION;
exports.TRADING_MODE_NO_TRADING = TRADING_MODE_NO_TRADING;
exports.TRADING_MODE_OPENING_AUCTION = TRADING_MODE_OPENING_AUCTION;
exports.TRADING_MODE_UNSPECIFIED = TRADING_MODE_UNSPECIFIED;
exports.decode = decode;
exports.encode = encode;
exports.encodingLength = encodingLength;
exports.parse = parse;
exports.stringify = stringify;
