/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { ListValue } from '../ListValue'
export function encode(
  obj?: PartialDeep<ListValue>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
