/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')

const _vega_DataSourceSpecConfigurationTime = require('./../DataSourceSpecConfigurationTime/decode.js')
const _vega_DataSourceSpecConfigurationTimeTrigger = require('./../DataSourceSpecConfigurationTimeTrigger/decode.js')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$sourceType = null
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$sourceType = {
          time: _vega_DataSourceSpecConfigurationTime.decode(data)
        }
        break

      case 2:
        field$sourceType = {
          timeTrigger: _vega_DataSourceSpecConfigurationTimeTrigger.decode(data)
        }
        break
    }
  }
  return { sourceType: field$sourceType }
}
