'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$factorLong = 0;
  let field$factorShort = 0;
  let field$maxMoveUp = 0;
  let field$minMoveDown = 0;
  let field$probabilityOfTrading = 0;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$factorLong = types.double(data);
        break

      case 2:
        field$factorShort = types.double(data);
        break

      case 3:
        field$maxMoveUp = types.double(data);
        break

      case 4:
        field$minMoveDown = types.double(data);
        break

      case 5:
        field$probabilityOfTrading = types.double(data);
        break
    }
  }
  return {
    factorLong: field$factorLong,
    factorShort: field$factorShort,
    maxMoveUp: field$maxMoveUp,
    minMoveDown: field$minMoveDown,
    probabilityOfTrading: field$probabilityOfTrading
  }
}

exports.decode = decode;
