'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.factorLong) writer.fixed64(1, obj.factorLong, types.double);
  if (obj.factorShort) writer.fixed64(2, obj.factorShort, types.double);
  if (obj.maxMoveUp) writer.fixed64(3, obj.maxMoveUp, types.double);
  if (obj.minMoveDown) writer.fixed64(4, obj.minMoveDown, types.double);
  if (obj.probabilityOfTrading)
    writer.fixed64(5, obj.probabilityOfTrading, types.double);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
