/// autogenerated by protoc-plugin-js
import type { AssetDetailsUpdate } from '../AssetDetailsUpdate'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): AssetDetailsUpdate
