/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { string } = require('protobuf-codec/encode/types')
const _vega_ERC20Update = require('./../ERC20Update/encode.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.quantum) writer.bytes(5, obj.quantum, string)

  if (obj.source?.erc20 ?? obj.erc20)
    writer.bytes(101, _vega_ERC20Update.encode(obj.source?.erc20 ?? obj.erc20))

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
