/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { AssetDetailsUpdate } from '../AssetDetailsUpdate'
export function encode(
  obj?: PartialDeep<AssetDetailsUpdate>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
