/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { uint64, string } = require('protobuf-codec/decode/types')
const _vega_DispatchStrategy = require('./../DispatchStrategy/decode.js')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$startEpoch = 0n
  let field$endEpoch = null
  let field$dispatchStrategy = null
  let field$factor = ''
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$startEpoch = uint64(data)
        break

      case 2:
        field$endEpoch = uint64(data)
        break

      case 3:
        field$dispatchStrategy = _vega_DispatchStrategy.decode(data)
        break

      case 4:
        field$factor = string(data)
        break
    }
  }
  return {
    startEpoch: field$startEpoch,
    endEpoch: field$endEpoch,
    dispatchStrategy: field$dispatchStrategy,
    factor: field$factor
  }
}
