/// autogenerated by protoc-plugin-js
import type { RecurringTransfer } from '../RecurringTransfer'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): RecurringTransfer
