/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { uint64, string } = require('protobuf-codec/encode/types')
const _vega_DispatchStrategy = require('./../DispatchStrategy/encode.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.startEpoch) writer.varint(1, obj.startEpoch, uint64)
  if (obj.endEpoch) writer.varint(2, obj.endEpoch, uint64)
  if (obj.dispatchStrategy)
    writer.bytes(3, _vega_DispatchStrategy.encode(obj.dispatchStrategy))
  if (obj.factor) writer.bytes(4, obj.factor, string)

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
