'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.peakSize) writer.varint(1, obj.peakSize, types.uint64);
  if (obj.minimumVisibleSize) writer.varint(2, obj.minimumVisibleSize, types.uint64);
  if (obj.reservedRemaining) writer.varint(3, obj.reservedRemaining, types.uint64);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
