'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$tid = '';
  let field$nonce = 0n;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$tid = types.string(data);
        break

      case 2:
        field$nonce = types.uint64(data);
        break
    }
  }
  return { tid: field$tid, nonce: field$nonce }
}

exports.decode = decode;
