'use strict';

var Writer = require('protobuf-codec/encode/writer');
var encode$1 = require('../LedgerEntry/encode.cjs');
var encode$2 = require('../PostTransferBalance/encode.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.entries?.length)
    obj.entries.forEach((v) => writer.bytes(1, encode$1.encode(v)));
  if (obj.balances?.length)
    obj.balances.forEach((v) =>
      writer.bytes(2, encode$2.encode(v))
    );

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
