/// autogenerated by protoc-plugin-js
import type { ProtocolUpgradeProposal } from '../ProtocolUpgradeProposal'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): ProtocolUpgradeProposal
