/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { uint64, string } = require('protobuf-codec/encode/types')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.upgradeBlockHeight) writer.varint(1, obj.upgradeBlockHeight, uint64)
  if (obj.vegaReleaseTag) writer.bytes(2, obj.vegaReleaseTag, string)

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
