/// autogenerated by protoc-plugin-js
const reader = require('protobuf-codec/decode/reader')
const { string } = require('protobuf-codec/decode/types')

exports.decode = function decode(
  buf,
  byteOffset = 0,
  byteLength = buf.byteLength
) {
  let field$minimumStakedTokens = ''
  let field$referralRewardMultiplier = ''
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$minimumStakedTokens = string(data)
        break

      case 2:
        field$referralRewardMultiplier = string(data)
        break
    }
  }
  return {
    minimumStakedTokens: field$minimumStakedTokens,
    referralRewardMultiplier: field$referralRewardMultiplier
  }
}
