/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { IcebergOrder } from '../IcebergOrder'
export function encode(
  obj?: PartialDeep<IcebergOrder>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
