'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$lifetimeLimit = '';
  let field$withdrawThreshold = '';
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$lifetimeLimit = types.string(data);
        break

      case 2:
        field$withdrawThreshold = types.string(data);
        break
    }
  }
  return {
    lifetimeLimit: field$lifetimeLimit,
    withdrawThreshold: field$withdrawThreshold
  }
}

exports.decode = decode;
