/// autogenerated by protoc-plugin-js
import type { OneOffTransfer } from '../OneOffTransfer'
export function decode(
  buf: Uint8Array,
  byteOffset?: number,
  byteLength?: number
): OneOffTransfer
