/// autogenerated by protoc-plugin-js
import type { PartialDeep } from 'type-fest'

import type { Fees } from '../Fees'
export function encode(
  obj?: PartialDeep<Fees>,
  buf?: Uint8Array,
  byteOffset?: number
): Uint8Array
