'use strict';

var reader = require('protobuf-codec/decode/reader');
var decode$1 = require('../DataSourceSpecConfigurationTime/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$source_type = null;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$source_type = {
          time: decode$1.decode(data)
        };
        break
    }
  }
  return { source_type: field$source_type }
}

exports.decode = decode;
