'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');
var decode$1 = require('../PriceMonitoringTrigger/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$minValidPrice = '';
  let field$maxValidPrice = '';
  let field$trigger = {};
  let field$referencePrice = '';
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$minValidPrice = types.string(data);
        break

      case 2:
        field$maxValidPrice = types.string(data);
        break

      case 3:
        field$trigger = decode$1.decode(data);
        break

      case 4:
        field$referencePrice = types.string(data);
        break
    }
  }
  return {
    minValidPrice: field$minValidPrice,
    maxValidPrice: field$maxValidPrice,
    trigger: field$trigger,
    referencePrice: field$referencePrice
  }
}

exports.decode = decode;
