'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');
var encode$1 = require('../PriceMonitoringTrigger/encode.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.minValidPrice) writer.bytes(1, obj.minValidPrice, types.string);
  if (obj.maxValidPrice) writer.bytes(2, obj.maxValidPrice, types.string);
  if (obj.trigger)
    writer.bytes(3, encode$1.encode(obj.trigger));
  if (obj.referencePrice) writer.bytes(4, obj.referencePrice, types.string);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
