'use strict';

var Writer = require('protobuf-codec/encode/writer');
var types = require('protobuf-codec/encode/types');
var encode$1 = require('../AccountDetails/encode.cjs');
var TransferType = require('../TransferType.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.fromAccount)
    writer.bytes(1, encode$1.encode(obj.fromAccount));
  if (obj.toAccount) writer.bytes(2, encode$1.encode(obj.toAccount));
  if (obj.amount) writer.bytes(3, obj.amount, types.string);
  if (obj.type) writer.varint(4, obj.type, TransferType);
  if (obj.timestamp) writer.varint(5, obj.timestamp, types.int64);
  if (obj.fromAccountBalance) writer.bytes(6, obj.fromAccountBalance, types.string);
  if (obj.toAccountBalance) writer.bytes(7, obj.toAccountBalance, types.string);

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
