name: regenerate-protos-cron

on:
  push
  # schedule:
  #   - cron: "0 * * * *"

jobs:
  check-for-new-version:
    outputs:
      new-version: ${{ steps.version.outputs.new-version }}
      current-version: ${{ steps.version.outputs.current-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: current-vega-version
        name: Get current version of vega generated against
        run: echo "version=$(cat ./vega-version.txt)" >> $GITHUB_OUTPUT
      - name: Test output
        run: echo ${{ steps.current-vega-version.outputs.version }}
      - id: version
        uses: vegaprotocol/github-action-get-vega-version@v0.0.1
        with:
          include-preview-versions: true
          previous-version: ${{ steps.current-vega-version.outputs.version }}
  regenerate-protos:
    needs: check-for-new-version
    runs-on: ubuntu-latest
    if: ${{ needs.check-for-new-version.outputs.new-version }}
    steps:
      - run: echo ${{ needs.check-for-new-version.outputs.current-version }}
