name: regenerate-protos

on:
  push
  # schedule:
  #   - cron: "0 * * * *"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/@vegaprotocol/vega-version-action
      with:
        include-preview-versions: true
      - run: echo 'done'
