name: regenerate-protos

on:
  push
  # schedule:
  #   - cron: "0 * * * *"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: generated-version
        run: echo "VERSION=$(cat ./vega-version.txt)" >> $GITHUB_ENV
      - name: Test output
        run: echo ${{ env.VERSION }}
      - id: version
        uses: vegaprotocol/github-action-get-vega-version@main
        with:
          include-preview-versions: true
          previous-version: ${{ env.VERSION }}
      - run: echo ${{ steps.version.outputs.new-version }}
      - run: echo ${{ steps.version.outputs.current-version }}
      - run: echo "running"
        if: ${{ steps.version.outputs.new-version }}
