name: regenerate-protos

on:
  push
  # schedule:
  #   - cron: "0 * * * *"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: get-repo-version
        run: echo "version=$(cat ./vega-version.js)" >> $GITHUB_OUTPUT
      - id: version
        uses: vegaprotocol/github-action-get-vega-version@main
        with:
          include-preview-versions: true
          previous-version: ${{ steps.get-repo-version.outputs.version }}
      - run: echo ${{ steps.version.outputs.new-version }}
      - run: echo ${{ steps.version.outputs.current-version }}
      - run: echo "running"
        if: ${{ steps.version.outputs.new-version }}
