name: regenerate-protos

on:
  push
  # schedule:
  #   - cron: "0 * * * *"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: version
        uses: vegaprotocol/github-action-get-vega-version@main
        with:
          include-preview-versions: true
      - run: echo ${{ steps.version.outputs.new-version }}
      - run: echo ${{ steps.version.outputs.current-version }}
