/// autogenerated by protoc-plugin-js
const Writer = require('protobuf-codec/encode/writer')
const { string, int64 } = require('protobuf-codec/encode/types')
const _vega_MarginMode = require('./../MarginMode.js')

exports.encode = function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer()

  if (obj.maintenanceMargin) writer.bytes(1, obj.maintenanceMargin, string)
  if (obj.searchLevel) writer.bytes(2, obj.searchLevel, string)
  if (obj.initialMargin) writer.bytes(3, obj.initialMargin, string)
  if (obj.collateralReleaseLevel)
    writer.bytes(4, obj.collateralReleaseLevel, string)
  if (obj.partyId) writer.bytes(5, obj.partyId, string)
  if (obj.marketId) writer.bytes(6, obj.marketId, string)
  if (obj.asset) writer.bytes(7, obj.asset, string)
  if (obj.timestamp) writer.varint(8, obj.timestamp, int64)
  if (obj.orderMargin) writer.bytes(9, obj.orderMargin, string)
  if (obj.marginMode) writer.varint(10, obj.marginMode, _vega_MarginMode)
  if (obj.marginFactor) writer.bytes(11, obj.marginFactor, string)

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }
