'use strict';

var Writer = require('protobuf-codec/encode/writer');
var encode$1 = require('../ScalingFactors/encode.cjs');

/// autogenerated by protoc-plugin-js

function encode(obj = {}, buf, byteOffset = 0) {
  const writer = new Writer();

  if (obj.scalingFactors)
    writer.bytes(1, encode$1.encode(obj.scalingFactors));

  return writer.concat(buf, byteOffset)
}

// export function encodingLength (obj) {
//   throw new Error('Unimplemented')
// }

exports.encode = encode;
