'use strict';

var reader = require('protobuf-codec/decode/reader');
var types = require('protobuf-codec/decode/types');
var decode$1 = require('../PriceLevel/decode.cjs');

/// autogenerated by protoc-plugin-js

function decode(buf, byteOffset = 0, byteLength = buf.byteLength) {
  let field$marketId = '';
  const field$buy = [];
  const field$sell = [];
  let field$sequenceNumber = 0n;
  for (const [field, { data }] of reader(buf, byteOffset, byteLength)) {
    switch (field) {
      case 1:
        field$marketId = types.string(data);
        break

      case 2:
        field$buy.push(decode$1.decode(data));
        break

      case 3:
        field$sell.push(decode$1.decode(data));
        break

      case 4:
        field$sequenceNumber = types.uint64(data);
        break
    }
  }
  return {
    marketId: field$marketId,
    buy: field$buy,
    sell: field$sell,
    sequenceNumber: field$sequenceNumber
  }
}

exports.decode = decode;
